export const TWITTER_50 = [
  {
    "id": "x50-voltage",
    "index": 87,
    "bucket": "impression",
    "url": "https://x.com/avstorm/status/1620087443927228417",
    "author": "avstorm",
    "views": 1280005,
    "likes": 5259,
    "reposts": 327,
    "metric": "views",
    "score": 1280005,
    "name": "High voltage",
    "label": "High Voltage",
    "blurb": "Andreas Storm's 1.2M-view electric CTA — cyan bolt ticks leak from a dark pill on hover.",
    "style_note": "Dark pill, electric cyan sparks, jitter on hover, bolt glyph.",
    "marker": "--x50-voltage-spark",
    "kind": "voltage",
    "fill": "#0b0d12",
    "ink": "#e8fbff",
    "accent": "#7af0ff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "high voltage",
      "voltage",
      "avstorm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-voltage-spark",
      "dark pill, electric cyan sparks, jitter"
    ]
  },
  {
    "id": "x50-loved-cta",
    "index": 88,
    "bucket": "impression",
    "url": "https://x.com/avstorm/status/1724521641953071141",
    "author": "avstorm",
    "views": 288685,
    "likes": 1062,
    "reposts": 57,
    "metric": "views",
    "score": 288685,
    "name": "Loved blend",
    "label": "Love this",
    "blurb": "Storm's 'Love this button' — a white pill with mix-blend-mode: difference that inverts the color field behind it.",
    "style_note": "White pill, mix-blend-mode: difference, colorful well.",
    "marker": "--x50-loved-blend",
    "kind": "loved-blend",
    "fill": "#ffffff",
    "ink": "#000000",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "loved blend",
      "love this",
      "loved-blend",
      "avstorm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-loved-blend",
      "white pill, mix-blend-mode: difference,"
    ]
  },
  {
    "id": "x50-height-hover",
    "index": 89,
    "bucket": "impression",
    "url": "https://x.com/avstorm/status/1646204829826445312",
    "author": "avstorm",
    "views": 230400,
    "likes": 1685,
    "reposts": 109,
    "metric": "views",
    "score": 230400,
    "name": "Height hover",
    "label": "Write",
    "blurb": "Height.app's next-level hover — a superellipse whose rainbow wash follows the pointer.",
    "style_note": "Soft superellipse, pastel rainbow wash, pointer-follow overlay.",
    "marker": "--x50-height-wash",
    "kind": "height",
    "fill": "#f6f3ee",
    "ink": "#1a1a1a",
    "accent": "#c4b5fd",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "height hover",
      "write",
      "height",
      "avstorm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-height-wash",
      "soft superellipse, pastel rainbow wash,"
    ]
  },
  {
    "id": "x50-cq-shimmer",
    "index": 90,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/1656423856276488192",
    "author": "jh3yy",
    "views": 228773,
    "likes": 1614,
    "reposts": 164,
    "metric": "views",
    "score": 228773,
    "name": "CQ shimmer",
    "label": "Shimmer",
    "blurb": "jhey's container-query shimmer — a spinning gradient slides 100cqw across the label.",
    "style_note": "container-type:size; translate calc(100cqw - 100%); spinning conic.",
    "marker": "--x50-cq-shimmer",
    "kind": "cq-shimmer",
    "fill": "#111827",
    "ink": "#f9fafb",
    "accent": "#fbbf24",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "cq shimmer",
      "shimmer",
      "cq-shimmer",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-cq-shimmer",
      "container-type:size; translate calc(100c"
    ]
  },
  {
    "id": "x50-blend-diff",
    "index": 91,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/1729546779274707150",
    "author": "jh3yy",
    "views": 152936,
    "likes": 1376,
    "reposts": 172,
    "metric": "views",
    "score": 152936,
    "name": "Invert spot",
    "label": "Hover",
    "blurb": "jhey's pointer-follow invert: a mix-blend-mode:difference spot tracks --x/--y instead of blending the whole pill.",
    "style_note": "Scoped span.spot, mix-blend-mode: difference, --x/--y from pointer.",
    "marker": "--x50-invert-spot",
    "kind": "invert-spot",
    "fill": "#111111",
    "ink": "#fafafa",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "invert spot",
      "hover",
      "invert-spot",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-invert-spot",
      "scoped span.spot, mix-blend-mode: differ"
    ]
  },
  {
    "id": "x50-grid-spin",
    "index": 92,
    "bucket": "impression",
    "url": "https://x.com/wesbos/status/1866895899554926912",
    "author": "wesbos",
    "views": 177154,
    "likes": 2599,
    "reposts": 207,
    "metric": "views",
    "score": 177154,
    "name": "Grid spinner",
    "label": "Saving",
    "blurb": "Wes Bos's CSS-grid stack — label and spinner occupy one cell so width never jumps while busy.",
    "style_note": "display:grid; stacked label+spinner; visibility toggle; aria-busy.",
    "marker": "--x50-grid-spin",
    "kind": "grid-spin",
    "fill": "#101010",
    "ink": "#fafafa",
    "accent": "#a3e635",
    "states": "default, hover, focus-visible, active, disabled, loading",
    "keywords": [
      "grid spinner",
      "saving",
      "grid-spin",
      "wesbos",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-grid-spin",
      "display:grid; stacked label+spinner; vis"
    ]
  },
  {
    "id": "x50-glitch-flip",
    "index": 93,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/1762979019446698310",
    "author": "jh3yy",
    "views": 168490,
    "likes": 2712,
    "reposts": 262,
    "metric": "views",
    "score": 168490,
    "name": "Glitch flip",
    "label": "Click Me",
    "blurb": "Pseudo-element content flip — each glyph strobes through garbage characters on hover.",
    "style_note": "Per-char --i delay; @keyframes flip swapping content.",
    "marker": "--x50-glitch-flip",
    "kind": "glitch",
    "fill": "#050505",
    "ink": "#39ff14",
    "accent": "#ff00aa",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "glitch flip",
      "click me",
      "glitch",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-glitch-flip",
      "per-char --i delay; @keyframes flip swap"
    ]
  },
  {
    "id": "x50-shadow-border",
    "index": 94,
    "bucket": "impression",
    "url": "https://x.com/PixelJanitor/status/1623358514440859649",
    "author": "PixelJanitor",
    "views": 164711,
    "likes": 951,
    "reposts": 71,
    "metric": "views",
    "score": 164711,
    "name": "Shadow border",
    "label": "Campsite",
    "blurb": "Derek Briggs' Campsite trick — stacked box-shadows stand in for a 1px border so contrast holds on a drop shadow.",
    "style_note": "0 0 0 1px inset shadows as border; no border-width.",
    "marker": "--x50-shadow-border",
    "kind": "shadow-border",
    "fill": "#ffffff",
    "ink": "#111111",
    "accent": "#d6d3d1",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "shadow border",
      "campsite",
      "shadow-border",
      "pixeljanitor",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-shadow-border",
      "0 0 0 1px inset shadows as border; no bo"
    ]
  },
  {
    "id": "x50-tw-lab",
    "index": 95,
    "bucket": "impression",
    "url": "https://x.com/Ibelick/status/1747665649785041320",
    "author": "Ibelick",
    "views": 153805,
    "likes": 323,
    "reposts": 19,
    "metric": "views",
    "score": 153805,
    "name": "TW lab",
    "label": "Get started",
    "blurb": "Ibelick's Tailwind lab WIP — compact rounded CTA with a sliding underline micro-interaction.",
    "style_note": "Black rounded-xl, underline scaleX from left on hover.",
    "marker": "--x50-tw-lab",
    "kind": "tw-lab",
    "fill": "#09090b",
    "ink": "#fafafa",
    "accent": "#a1a1aa",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "tw lab",
      "get started",
      "tw-lab",
      "ibelick",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-tw-lab",
      "black rounded-xl, underline scalex from"
    ]
  },
  {
    "id": "x50-fifty-kit",
    "index": 96,
    "bucket": "impression",
    "url": "https://x.com/Ibelick/status/1749528182443651381",
    "author": "Ibelick",
    "views": 132159,
    "likes": 784,
    "reposts": 70,
    "metric": "views",
    "score": 132159,
    "name": "Fifty kit",
    "label": "Copy paste",
    "blurb": "The shipped +50 Tailwind kit — white-on-black with a diagonal shine that only runs once per hover.",
    "style_note": "Shine sweep ::after, no JS, copy-paste kit energy.",
    "marker": "--x50-fifty-kit",
    "kind": "fifty-kit",
    "fill": "#18181b",
    "ink": "#f4f4f5",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "fifty kit",
      "copy paste",
      "fifty-kit",
      "ibelick",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-fifty-kit",
      "shine sweep ::after, no js, copy-paste k"
    ]
  },
  {
    "id": "x50-pointer-down",
    "index": 97,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/2061453469995679910",
    "author": "jh3yy",
    "views": 118601,
    "likes": 565,
    "reposts": 28,
    "metric": "views",
    "score": 118601,
    "name": "Pointer down",
    "label": "Press me",
    "blurb": "cursor:pointer needs a pointerdown counterpart — the active frame swaps to a pressed-hand cursor and sinks 1px.",
    "style_note": "button:active { cursor + translateY(1px) }.",
    "marker": "--x50-pointer-down",
    "kind": "pointer-down",
    "fill": "#2563eb",
    "ink": "#eff6ff",
    "accent": "#1d4ed8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "pointer down",
      "press me",
      "pointer-down",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-pointer-down",
      "button:active { cursor + translatey(1px)"
    ]
  },
  {
    "id": "x50-inner-bevel",
    "index": 98,
    "bucket": "impression",
    "url": "https://x.com/jamesm/status/1622905711650050048",
    "author": "jamesm",
    "views": 111958,
    "likes": 740,
    "reposts": 40,
    "metric": "views",
    "score": 111958,
    "name": "Inner bevel",
    "label": "Bevel",
    "blurb": "James McDonald on Campsite luxury — outside stroke, inner highlight, then a soft drop shadow.",
    "style_note": "inset highlight + outside hairline + drop shadow.",
    "marker": "--x50-inner-bevel",
    "kind": "bevel",
    "fill": "#f3f1ec",
    "ink": "#1c1917",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "inner bevel",
      "bevel",
      "jamesm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-inner-bevel",
      "inset highlight + outside hairline + dro"
    ]
  },
  {
    "id": "x50-explore-3d",
    "index": 99,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/1644055788023939073",
    "author": "jh3yy",
    "views": 104416,
    "likes": 1199,
    "reposts": 135,
    "metric": "views",
    "score": 104416,
    "name": "Explore 3D",
    "label": "Explore",
    "blurb": "Glowy Explore — transform-style:preserve-3d planes and a conical glint that flips on hover.",
    "style_note": "preserve-3d inner planes, conical-gradient glint.",
    "marker": "--x50-explore-3d",
    "kind": "explore-3d",
    "fill": "#020617",
    "ink": "#e0f2fe",
    "accent": "#38bdf8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "explore 3d",
      "explore",
      "explore-3d",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-explore-3d",
      "preserve-3d inner planes, conical-gradie"
    ]
  },
  {
    "id": "x50-search-pill",
    "index": 100,
    "bucket": "impression",
    "url": "https://x.com/avstorm/status/2065322776718696683",
    "author": "avstorm",
    "views": 95970,
    "likes": 1065,
    "reposts": 10,
    "metric": "views",
    "score": 95970,
    "name": "Search pill",
    "label": "Search",
    "blurb": "Apple's tab-bar search button — a compact circle that expands into a pill and reveals the word Search.",
    "style_note": "Circle-to-pill width morph, magnifier then label.",
    "marker": "--x50-search-pill",
    "kind": "search-pill",
    "fill": "#e8e8ed",
    "ink": "#1d1d1f",
    "accent": "#0071e3",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "search pill",
      "search",
      "search-pill",
      "avstorm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-search-pill",
      "circle-to-pill width morph, magnifier th"
    ]
  },
  {
    "id": "x50-liquid-css",
    "index": 101,
    "bucket": "impression",
    "url": "https://x.com/avstorm/status/1991487168125235215",
    "author": "avstorm",
    "views": 71458,
    "likes": 1465,
    "reposts": 96,
    "metric": "views",
    "score": 71458,
    "name": "Liquid CSS",
    "label": "Liquid",
    "blurb": "Liquid Glass with CSS and SVG — frosted fill, specular edge, and a slow caustic drift.",
    "style_note": "backdrop-filter blur, SVG-like specular gradient, caustic drift.",
    "marker": "--x50-liquid-css",
    "kind": "liquid-css",
    "fill": "rgba(255,255,255,.22)",
    "ink": "#0f172a",
    "accent": "#94a3b8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "liquid css",
      "liquid",
      "liquid-css",
      "avstorm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-liquid-css",
      "backdrop-filter blur, svg-like specular"
    ]
  },
  {
    "id": "x50-conic-p3",
    "index": 102,
    "bucket": "impression",
    "url": "https://x.com/LukyVJ/status/1646927645425164313",
    "author": "LukyVJ",
    "views": 62356,
    "likes": 265,
    "reposts": 22,
    "metric": "views",
    "score": 62356,
    "name": "Conic P3",
    "label": "Rainbow",
    "blurb": "Luky's Height take — a display-p3 conic gradient tracks the cursor behind overflow:hidden.",
    "style_note": "conic-gradient + --mx/--my from pointer + inner shadow.",
    "marker": "--x50-conic-p3",
    "kind": "conic-p3",
    "fill": "#fffdf8",
    "ink": "#111111",
    "accent": "#ff6b9d",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "conic p3",
      "rainbow",
      "conic-p3",
      "lukyvj",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-conic-p3",
      "conic-gradient + --mx/--my from pointer"
    ]
  },
  {
    "id": "x50-overlay-cta",
    "index": 103,
    "bucket": "impression",
    "url": "https://x.com/profounderx/status/2088747134761714168",
    "author": "profounderx",
    "views": 56868,
    "likes": 283,
    "reposts": 32,
    "metric": "views",
    "score": 56868,
    "name": "Overlay CTA",
    "label": "Watch now",
    "blurb": "Profounder's free CTA overlay maker — a lower-third capsule with a play chevron and sliding fill.",
    "style_note": "Capsule, play triangle, left-to-right fill on hover.",
    "marker": "--x50-overlay-cta",
    "kind": "overlay-cta",
    "fill": "#ef4444",
    "ink": "#fff",
    "accent": "#fecaca",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "overlay cta",
      "watch now",
      "overlay-cta",
      "profounderx",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-overlay-cta",
      "capsule, play triangle, left-to-right fi"
    ]
  },
  {
    "id": "x50-haptic",
    "index": 104,
    "bucket": "impression",
    "url": "https://x.com/oguzyagizkara/status/1636391069981216773",
    "author": "oguzyagizkara",
    "views": 45580,
    "likes": 349,
    "reposts": 19,
    "metric": "views",
    "score": 45580,
    "name": "Haptic press",
    "label": "Haptic",
    "blurb": "Oğuz's haptic experiment — a thick rounded key that squashes, then springs back with a shadow pulse.",
    "style_note": "scale(0.96) squash, spring shadow, tactile depth.",
    "marker": "--x50-haptic",
    "kind": "haptic",
    "fill": "#f4f1ea",
    "ink": "#1a1a1a",
    "accent": "#c4bfb4",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "haptic press",
      "haptic",
      "oguzyagizkara",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-haptic",
      "scale(0.96) squash, spring shadow, tacti"
    ]
  },
  {
    "id": "x50-layer-step",
    "index": 105,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/1633136634546864130",
    "author": "jh3yy",
    "views": 43724,
    "likes": 425,
    "reposts": 39,
    "metric": "views",
    "score": 43724,
    "name": "Layer step",
    "label": "Layer",
    "blurb": "Scoped custom properties step a stacked label by --step on hover and half-step on active.",
    "style_note": "--step:0.5rem; --a 0→1→0.5; translate calc(var(--a)*var(--step)).",
    "marker": "--x50-layer-step",
    "kind": "layer-step",
    "fill": "#0a0a0a",
    "ink": "#fafafa",
    "accent": "#737373",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "layer step",
      "layer",
      "layer-step",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-layer-step",
      "--step:0.5rem; --a 0→1→0.5; translate ca"
    ]
  },
  {
    "id": "x50-css-challenge",
    "index": 106,
    "bucket": "impression",
    "url": "https://x.com/zainab_nisa_/status/1610174059051978753",
    "author": "zainab_nisa_",
    "views": 40551,
    "likes": 334,
    "reposts": 53,
    "metric": "views",
    "score": 40551,
    "name": "CSS challenge",
    "label": "Accept",
    "blurb": "Zainab's hover-challenge CTA — staggered box-shadow rings bloom out on hover.",
    "style_note": "Multi-layer box-shadow rings with delay.",
    "marker": "--x50-css-challenge",
    "kind": "challenge",
    "fill": "#7c3aed",
    "ink": "#f5f3ff",
    "accent": "#c4b5fd",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "css challenge",
      "accept",
      "challenge",
      "zainab_nisa_",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-css-challenge",
      "multi-layer box-shadow rings with delay."
    ]
  },
  {
    "id": "x50-dir-roll",
    "index": 107,
    "bucket": "impression",
    "url": "https://x.com/jh3yy/status/1804121320138965284",
    "author": "jh3yy",
    "views": 40407,
    "likes": 801,
    "reposts": 58,
    "metric": "views",
    "score": 40407,
    "name": "Direction roll",
    "label": "Hover",
    "blurb": "Direction-aware CSS using lh + text-shadow clones — the word rolls 1lh toward the hovered half.",
    "style_note": "text-shadow 0 1lh; translate 0 var(--y); linear() spring.",
    "marker": "--x50-dir-roll",
    "kind": "dir-roll",
    "fill": "#111111",
    "ink": "#f5f5f5",
    "accent": "#f5f5f5",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "direction roll",
      "hover",
      "dir-roll",
      "jh3yy",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-dir-roll",
      "text-shadow 0 1lh; translate 0 var(--y);"
    ]
  },
  {
    "id": "x50-border-beam",
    "index": 108,
    "bucket": "impression",
    "url": "https://x.com/MengTo/status/2024780143546216465",
    "author": "MengTo",
    "views": 37364,
    "likes": 397,
    "reposts": 30,
    "metric": "views",
    "score": 37364,
    "name": "Border beam",
    "label": "Dive in",
    "blurb": "Meng To's Aura prompt — a 1px border beam races around a pill on hover.",
    "style_note": "Rotating conic mask as 1px border beam.",
    "marker": "--x50-border-beam",
    "kind": "border-beam",
    "fill": "#0b0f19",
    "ink": "#f8fafc",
    "accent": "#60a5fa",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "border beam",
      "dive in",
      "border-beam",
      "mengto",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-border-beam",
      "rotating conic mask as 1px border beam."
    ]
  },
  {
    "id": "x50-wwdc-gloss",
    "index": 109,
    "bucket": "impression",
    "url": "https://x.com/jamesm/status/1929898983859556359",
    "author": "jamesm",
    "views": 19764,
    "likes": 240,
    "reposts": 2,
    "metric": "views",
    "score": 19764,
    "name": "WWDC gloss",
    "label": "Continue",
    "blurb": "James's WWDC25-style glossy white button — candy highlight, inner shadow, aqua system ink.",
    "style_note": "Skeuomorphic white gloss, linear highlight, aqua label.",
    "marker": "--x50-wwdc-gloss",
    "kind": "wwdc-gloss",
    "fill": "#f5f5f7",
    "ink": "#0071e3",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "wwdc gloss",
      "continue",
      "wwdc-gloss",
      "jamesm",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-wwdc-gloss",
      "skeuomorphic white gloss, linear highlig"
    ]
  },
  {
    "id": "x50-five-hovers",
    "index": 110,
    "bucket": "impression",
    "url": "https://x.com/NanouuSymeon/status/1902665268142195103",
    "author": "NanouuSymeon",
    "views": 24688,
    "likes": 549,
    "reposts": 77,
    "metric": "views",
    "score": 24688,
    "name": "Five hovers",
    "label": "Hover me",
    "blurb": "Nanou's five CSS hover recipes distilled to one — background slides up to invert the type.",
    "style_note": "Background slide from bottom covering the label.",
    "marker": "--x50-five-hovers",
    "kind": "five-hovers",
    "fill": "#ffffff",
    "ink": "#111827",
    "accent": "#111827",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "five hovers",
      "hover me",
      "five-hovers",
      "nanouusymeon",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-five-hovers",
      "background slide from bottom covering th"
    ]
  },
  {
    "id": "x50-disco-load",
    "index": 111,
    "bucket": "impression",
    "url": "https://x.com/joebell_/status/1557355193473585153",
    "author": "joebell_",
    "views": null,
    "likes": 2147,
    "reposts": 122,
    "metric": "likes_reposts",
    "score": 2269,
    "name": "Loading disco",
    "label": "Disco",
    "blurb": "Joe Bell's loading disco — a gap instead of a border, conic-gradient spinning in the reveal.",
    "style_note": "Gap ring, rotating conic, aria-busy on click.",
    "marker": "--x50-disco-load",
    "kind": "disco",
    "fill": "#0c0c0c",
    "ink": "#fafafa",
    "accent": "#f472b6",
    "states": "default, hover, focus-visible, active, disabled, loading",
    "keywords": [
      "loading disco",
      "disco",
      "joebell_",
      "impression",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-disco-load",
      "gap ring, rotating conic, aria-busy on c"
    ]
  },
  {
    "id": "x50-gravity",
    "index": 112,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1794998606325498004",
    "author": "anatudor",
    "views": 18972,
    "likes": 77,
    "reposts": 13,
    "metric": "views",
    "score": 18972,
    "name": "Gravity CSS",
    "label": "Gravity",
    "blurb": "Ana Tudor's 1K-heart CodePen gravity button — orbs fall and pile along the baseline, then hop on hover.",
    "style_note": "Pseudo orbs with gravity keyframes; don't-use-in-the-wild craft.",
    "marker": "--x50-gravity",
    "kind": "gravity",
    "fill": "#111827",
    "ink": "#fde68a",
    "accent": "#f59e0b",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "gravity css",
      "gravity",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-gravity",
      "pseudo orbs with gravity keyframes; don'"
    ]
  },
  {
    "id": "x50-drop-layer",
    "index": 113,
    "bucket": "underrated",
    "url": "https://x.com/jamesm/status/1622905785629155330",
    "author": "jamesm",
    "views": 13059,
    "likes": 69,
    "reposts": 1,
    "metric": "views",
    "score": 13059,
    "name": "Drop finish",
    "label": "Finish",
    "blurb": "Step 4 of the Campsite thread — the finishing drop-shadow layer that blends the bevel into the well.",
    "style_note": "Soft Y-offset drop shadow, hairline stroke, grey well.",
    "marker": "--x50-drop-finish",
    "kind": "drop-finish",
    "fill": "#eceae4",
    "ink": "#292524",
    "accent": "#a8a29e",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "drop finish",
      "finish",
      "drop-finish",
      "jamesm",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-drop-finish",
      "soft y-offset drop shadow, hairline stro"
    ]
  },
  {
    "id": "x50-julius-glass",
    "index": 114,
    "bucket": "underrated",
    "url": "https://x.com/Ciri_ai/status/2092560883801375066",
    "author": "Ciri_ai",
    "views": 12480,
    "likes": 82,
    "reposts": 1,
    "metric": "views",
    "score": 12480,
    "name": "Julius glass",
    "label": "Glass",
    "blurb": "Ciri's Julius-built liquid glass — tap cycles idle/busy/done while the frosted pill morphs.",
    "style_note": "State cycle on click, frosted Apple glass.",
    "marker": "--x50-julius-glass",
    "kind": "julius-glass",
    "fill": "rgba(255,255,255,.4)",
    "ink": "#0a0a0a",
    "accent": "#cbd5e1",
    "states": "default, hover, focus-visible, active, disabled, loading",
    "keywords": [
      "julius glass",
      "glass",
      "julius-glass",
      "ciri_ai",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-julius-glass",
      "state cycle on click, frosted apple glas"
    ]
  },
  {
    "id": "x50-syntax-glass",
    "index": 115,
    "bucket": "underrated",
    "url": "https://x.com/wesbos/status/1961448086640730435",
    "author": "wesbos",
    "views": 10731,
    "likes": 65,
    "reposts": 3,
    "metric": "views",
    "score": 10731,
    "name": "Syntax glass",
    "label": "Syntax",
    "blurb": "Wes vs Scott's Syntax.fm glass CTA — stacked translucent plates with a hard inner highlight.",
    "style_note": "Layered translucent plates, yellow Syntax accent.",
    "marker": "--x50-syntax-glass",
    "kind": "syntax-glass",
    "fill": "rgba(20,20,20,.55)",
    "ink": "#facc15",
    "accent": "#fde047",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "syntax glass",
      "syntax",
      "syntax-glass",
      "wesbos",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-syntax-glass",
      "layered translucent plates, yellow synta"
    ]
  },
  {
    "id": "x50-altitude",
    "index": 116,
    "bucket": "underrated",
    "url": "https://x.com/jamesm/status/1932958811868049720",
    "author": "jamesm",
    "views": 10276,
    "likes": 125,
    "reposts": 1,
    "metric": "views",
    "score": 10276,
    "name": "Send email",
    "label": "Send email",
    "blurb": "James's 35,000ft Wireframe specimen — a skeuomorphic glossy capsule labeled Send email.",
    "style_note": "Light gray glossy capsule, inset highlight, drop shadow, Send email.",
    "marker": "--x50-send-email",
    "kind": "send-email",
    "fill": "#ececee",
    "ink": "#1d1d1f",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "send email",
      "send-email",
      "jamesm",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-send-email",
      "light gray glossy capsule, inset highlig"
    ]
  },
  {
    "id": "x50-ana-soft",
    "index": 117,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1634909243370360834",
    "author": "anatudor",
    "views": 4224,
    "likes": 14,
    "reposts": 3,
    "metric": "views",
    "score": 4224,
    "name": "iOS gloss",
    "label": "Soft",
    "blurb": "Ana's CodePen soft set — the yellow iOS-like rounded square with candy gloss from the photo.",
    "style_note": "Yellow-orange linear-gradient square, 22px radius, top gloss, press darken.",
    "marker": "--x50-ios-yellow",
    "kind": "ios-yellow",
    "fill": "#ffe34d",
    "ink": "#7a4a00",
    "accent": "#ff9f00",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "ios gloss",
      "soft",
      "ios-yellow",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-ios-yellow",
      "yellow-orange linear-gradient square, 22"
    ]
  },
  {
    "id": "x50-glass-mix",
    "index": 118,
    "bucket": "underrated",
    "url": "https://x.com/PixelJanitor/status/1930653220139085904",
    "author": "PixelJanitor",
    "views": 3811,
    "likes": 76,
    "reposts": 0,
    "metric": "views",
    "score": 3811,
    "name": "Glass mix",
    "label": "Frost",
    "blurb": "PixelJanitor mixing avstorm + jamesm glass — dual speculars and a hairline rim.",
    "style_note": "Two speculars, hairline rim, frost fill.",
    "marker": "--x50-glass-mix",
    "kind": "glass-mix",
    "fill": "rgba(248,250,252,.5)",
    "ink": "#0f172a",
    "accent": "#e2e8f0",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "glass mix",
      "frost",
      "glass-mix",
      "pixeljanitor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-glass-mix",
      "two speculars, hairline rim, frost fill."
    ]
  },
  {
    "id": "x50-scroll-mark",
    "index": 119,
    "bucket": "underrated",
    "url": "https://x.com/jh3yy/status/2093469946848157753",
    "author": "jh3yy",
    "views": 3282,
    "likes": 25,
    "reposts": 1,
    "metric": "views",
    "score": 3282,
    "name": "Scroll marker",
    "label": "Next",
    "blurb": "jhey on ::scroll-button + ::scroll-marker — a chevron capsule that nudges as if advancing a scroller.",
    "style_note": "Chevron translate on hover, capsule, scroll-button energy.",
    "marker": "--x50-scroll-mark",
    "kind": "scroll-mark",
    "fill": "#18181b",
    "ink": "#fafafa",
    "accent": "#d4d4d8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "scroll marker",
      "next",
      "scroll-mark",
      "jh3yy",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-scroll-mark",
      "chevron translate on hover, capsule, scr"
    ]
  },
  {
    "id": "x50-retro-2010",
    "index": 120,
    "bucket": "underrated",
    "url": "https://x.com/Ibelick/status/1765813460619731111",
    "author": "Ibelick",
    "views": 2822,
    "likes": 32,
    "reposts": 0,
    "metric": "views",
    "score": 2822,
    "name": "2010s vibe",
    "label": "Download",
    "blurb": "Ibelick's 2010s kit — glossy blue gradient, 1px highlight, that era's Download CTA.",
    "style_note": "Web 2.0 blue gradient, top highlight, inset press.",
    "marker": "--x50-retro-2010",
    "kind": "retro-2010",
    "fill": "#3b82f6",
    "ink": "#ffffff",
    "accent": "#1d4ed8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "2010s vibe",
      "download",
      "retro-2010",
      "ibelick",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-retro-2010",
      "web 2.0 blue gradient, top highlight, in"
    ]
  },
  {
    "id": "x50-proximity",
    "index": 121,
    "bucket": "underrated",
    "url": "https://x.com/ChallengesCss/status/2092662645593645236",
    "author": "ChallengesCss",
    "views": 2054,
    "likes": 28,
    "reposts": 7,
    "metric": "views",
    "score": 2054,
    "name": "Proximity hover",
    "label": "Near",
    "blurb": "Temani Afif's hover-proximity article — neighbors brighten when this button is hovered.",
    "style_note": "Sibling dim/bright via :has, proximity programming in CSS.",
    "marker": "--x50-proximity",
    "kind": "proximity",
    "fill": "#0f172a",
    "ink": "#e2e8f0",
    "accent": "#22d3ee",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "proximity hover",
      "near",
      "proximity",
      "challengescss",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-proximity",
      "sibling dim/bright via :has, proximity p"
    ]
  },
  {
    "id": "x50-metallic",
    "index": 122,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1634934029731635202",
    "author": "anatudor",
    "views": 1536,
    "likes": 11,
    "reposts": 0,
    "metric": "views",
    "score": 1536,
    "name": "Metallic set",
    "label": "Metal",
    "blurb": "Ana's metallic single-element buttons — brushed linear-gradient steel with a moving specular.",
    "style_note": "Brushed metal gradient, specular sweep.",
    "marker": "--x50-metallic",
    "kind": "metallic",
    "fill": "#9ca3af",
    "ink": "#111827",
    "accent": "#e5e7eb",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "metallic set",
      "metal",
      "metallic",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-metallic",
      "brushed metal gradient, specular sweep."
    ]
  },
  {
    "id": "x50-modern-sheet",
    "index": 123,
    "bucket": "underrated",
    "url": "https://x.com/NanouuSymeon/status/1930557204656001317",
    "author": "NanouuSymeon",
    "views": 1377,
    "likes": 16,
    "reposts": 1,
    "metric": "views",
    "score": 1377,
    "name": "Modern sheet",
    "label": "Modern",
    "blurb": "Nanou's modern CSS buttons sheet — a taut black rectangle with a 2px tracking label.",
    "style_note": "Tight tracking, square-ish, letter-spacing hover.",
    "marker": "--x50-modern-sheet",
    "kind": "modern-sheet",
    "fill": "#000000",
    "ink": "#ffffff",
    "accent": "#ffffff",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "modern sheet",
      "modern",
      "modern-sheet",
      "nanouusymeon",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-modern-sheet",
      "tight tracking, square-ish, letter-spaci"
    ]
  },
  {
    "id": "x50-proper-lg",
    "index": 124,
    "bucket": "underrated",
    "url": "https://x.com/_julianbp/status/1932815087888126069",
    "author": "_julianbp",
    "views": 1331,
    "likes": 6,
    "reposts": 0,
    "metric": "views",
    "score": 1331,
    "name": "Proper liquid",
    "label": "Liquid",
    "blurb": "Julian on how Liquid Glass should look — thick refraction, inner caustic, press squash.",
    "style_note": "Thick glass, inner caustic, squash press.",
    "marker": "--x50-proper-lg",
    "kind": "proper-lg",
    "fill": "rgba(226,232,240,.35)",
    "ink": "#0b1220",
    "accent": "#93c5fd",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "proper liquid",
      "liquid",
      "proper-lg",
      "_julianbp",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-proper-lg",
      "thick glass, inner caustic, squash press"
    ]
  },
  {
    "id": "x50-tw-ripple",
    "index": 125,
    "bucket": "underrated",
    "url": "https://x.com/Ibelick/status/1716427699520999815",
    "author": "Ibelick",
    "views": 1406,
    "likes": 16,
    "reposts": 1,
    "metric": "views",
    "score": 1406,
    "name": "Lab ripple",
    "label": "Ripple",
    "blurb": "Ibelick Lab ripple — ink expands from the click point in a Tailwind-shaped pill.",
    "style_note": "Click-origin ripple span, zinc pill.",
    "marker": "--x50-tw-ripple",
    "kind": "tw-ripple",
    "fill": "#27272a",
    "ink": "#fafafa",
    "accent": "rgba(255,255,255,.35)",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "lab ripple",
      "ripple",
      "tw-ripple",
      "ibelick",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-tw-ripple",
      "click-origin ripple span, zinc pill."
    ]
  },
  {
    "id": "x50-cross-ripple",
    "index": 126,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1901635325945840077",
    "author": "anatudor",
    "views": 1145,
    "likes": 28,
    "reposts": 3,
    "metric": "views",
    "score": 1145,
    "name": "Cross ripple",
    "label": "Wave",
    "blurb": "Ana's half-decade-old ripple, now cross-browser — radial ink from center using only CSS.",
    "style_note": "Pure CSS radial ink from center, no JS.",
    "marker": "--x50-cross-ripple",
    "kind": "cross-ripple",
    "fill": "#1e293b",
    "ink": "#f8fafc",
    "accent": "#38bdf8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "cross ripple",
      "wave",
      "cross-ripple",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-cross-ripple",
      "pure css radial ink from center, no js."
    ]
  },
  {
    "id": "x50-candy-ghost",
    "index": 127,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1634964314133241856",
    "author": "anatudor",
    "views": 926,
    "likes": 4,
    "reposts": 1,
    "metric": "views",
    "score": 926,
    "name": "Candy ghost",
    "label": "Ghost",
    "blurb": "Animated candy ghost — a translucent outline that fills with jelly color from the baseline.",
    "style_note": "Transparent fill, candy outline, jelly rise.",
    "marker": "--x50-candy-ghost",
    "kind": "candy-ghost",
    "fill": "transparent",
    "ink": "#db2777",
    "accent": "#f9a8d4",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "candy ghost",
      "ghost",
      "candy-ghost",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-candy-ghost",
      "transparent fill, candy outline, jelly r"
    ]
  },
  {
    "id": "x50-css-3d-btns",
    "index": 128,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1634945567985127424",
    "author": "anatudor",
    "views": 877,
    "likes": 3,
    "reposts": 0,
    "metric": "views",
    "score": 877,
    "name": "CSS 3D",
    "label": "Extrude",
    "blurb": "Ana's 3D pure-CSS buttons — a fake extrusion that shortens on press as if the block recedes.",
    "style_note": "box-shadow extrusion, press shortens the stack.",
    "marker": "--x50-css-3d",
    "kind": "css-3d",
    "fill": "#f97316",
    "ink": "#fff7ed",
    "accent": "#9a3412",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "css 3d",
      "extrude",
      "css-3d",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-css-3d",
      "box-shadow extrusion, press shortens the"
    ]
  },
  {
    "id": "x50-nerd-btn",
    "index": 129,
    "bucket": "underrated",
    "url": "https://x.com/Ibelick/status/1713632931866968083",
    "author": "Ibelick",
    "views": 875,
    "likes": 10,
    "reposts": 0,
    "metric": "views",
    "score": 875,
    "name": "Nerd button",
    "label": "button 🤓",
    "blurb": "Ibelick's one-word 'button 🤓' clip — a tiny zinc chip that wiggles ±2deg on hover.",
    "style_note": "Wiggle keyframes, emoji in the label, tiny chip.",
    "marker": "--x50-nerd-btn",
    "kind": "nerd",
    "fill": "#3f3f46",
    "ink": "#fafafa",
    "accent": "#a1a1aa",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "nerd button",
      "button 🤓",
      "nerd",
      "ibelick",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-nerd-btn",
      "wiggle keyframes, emoji in the label, ti"
    ]
  },
  {
    "id": "x50-3d-hover",
    "index": 130,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1916835575887208956",
    "author": "anatudor",
    "views": 821,
    "likes": 23,
    "reposts": 1,
    "metric": "views",
    "score": 821,
    "name": "3D hover",
    "label": "Tilt",
    "blurb": "Super-simple pure CSS 3D hover — rotateX/rotateY on a perspective wrapper.",
    "style_note": "perspective wrapper, rotateX 8deg / rotateY -10deg.",
    "marker": "--x50-3d-hover",
    "kind": "tilt3d",
    "fill": "#312e81",
    "ink": "#e0e7ff",
    "accent": "#818cf8",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "3d hover",
      "tilt",
      "tilt3d",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-3d-hover",
      "perspective wrapper, rotatex 8deg / rota"
    ]
  },
  {
    "id": "x50-button-sets",
    "index": 131,
    "bucket": "underrated",
    "url": "https://x.com/anatudor/status/1902270703593775342",
    "author": "anatudor",
    "views": 788,
    "likes": 19,
    "reposts": 1,
    "metric": "views",
    "score": 788,
    "name": "Download now",
    "label": "DOWNLOAD NOW",
    "blurb": "Ana's single-button set — floppy split joined to a cyan DOWNLOAD NOW ribbon.",
    "style_note": "Dark disk tab + cyan gradient ribbon, DOWNLOAD NOW, drop shadow.",
    "marker": "--x50-download-now",
    "kind": "download-now",
    "fill": "#1598b0",
    "ink": "#ffffff",
    "accent": "#2b3038",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "download now",
      "download-now",
      "anatudor",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-download-now",
      "dark disk tab + cyan gradient ribbon, do"
    ]
  },
  {
    "id": "x50-giana-dir",
    "index": 132,
    "bucket": "underrated",
    "url": "https://x.com/gianablantin/status/838663859619561473",
    "author": "gianablantin",
    "views": null,
    "likes": 400,
    "reposts": 109,
    "metric": "likes_reposts",
    "score": 509,
    "name": "Giana direction",
    "label": "From",
    "blurb": "2017 CSS-only directional hover — the fill enters from the side the pointer arrived.",
    "style_note": "Four edge hit-zones driving overlay origin.",
    "marker": "--x50-giana-dir",
    "kind": "giana-dir",
    "fill": "#111827",
    "ink": "#f9fafb",
    "accent": "#34d399",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "giana direction",
      "from",
      "giana-dir",
      "gianablantin",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-giana-dir",
      "four edge hit-zones driving overlay orig"
    ]
  },
  {
    "id": "x50-one-div",
    "index": 133,
    "bucket": "underrated",
    "url": "https://x.com/cassidoo/status/904949712511410176",
    "author": "cassidoo",
    "views": null,
    "likes": 166,
    "reposts": 25,
    "metric": "likes_reposts",
    "score": 191,
    "name": "One div",
    "label": "One",
    "blurb": "Cassidy's one-div hover — the single element grows a second color via box-shadow inset.",
    "style_note": "One element, inset box-shadow as the hover fill.",
    "marker": "--x50-one-div",
    "kind": "one-div",
    "fill": "#be185d",
    "ink": "#fff1f2",
    "accent": "#831843",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "one div",
      "one",
      "one-div",
      "cassidoo",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-one-div",
      "one element, inset box-shadow as the hov"
    ]
  },
  {
    "id": "x50-hover-active",
    "index": 134,
    "bucket": "underrated",
    "url": "https://x.com/raos3d/status/2092995189099106467",
    "author": "raos3d",
    "views": 196,
    "likes": 1,
    "reposts": 0,
    "metric": "views",
    "score": 196,
    "name": "Hover active",
    "label": "Active",
    "blurb": "raos3d: only hover and active — a 3D product-like block that tips forward then stamps down.",
    "style_note": "Hover tip, active stamp, no other states needed.",
    "marker": "--x50-hover-active",
    "kind": "hover-active",
    "fill": "#f8fafc",
    "ink": "#0f172a",
    "accent": "#64748b",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "hover active",
      "active",
      "hover-active",
      "raos3d",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-hover-active",
      "hover tip, active stamp, no other states"
    ]
  },
  {
    "id": "x50-fifteen",
    "index": 135,
    "bucket": "underrated",
    "url": "https://x.com/ChallengesCss/status/1592523730596642817",
    "author": "ChallengesCss",
    "views": null,
    "likes": 30,
    "reposts": 4,
    "metric": "likes_reposts",
    "score": 34,
    "name": "Fifteen decls",
    "label": "Tip",
    "blurb": "Temani's <15-declaration button — only the button tag, no pseudos, CSS variables for the lift.",
    "style_note": "No extra elements, no pseudos, var-driven lift.",
    "marker": "--x50-fifteen",
    "kind": "fifteen",
    "fill": "#2563eb",
    "ink": "#eff6ff",
    "accent": "#1e3a8a",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "fifteen decls",
      "tip",
      "fifteen",
      "challengescss",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-fifteen",
      "no extra elements, no pseudos, var-drive"
    ]
  },
  {
    "id": "x50-micro-scale",
    "index": 136,
    "bucket": "underrated",
    "url": "https://x.com/ryancuff_/status/2092603342270656540",
    "author": "ryancuff_",
    "views": 88,
    "likes": 1,
    "reposts": 0,
    "metric": "views",
    "score": 88,
    "name": "Micro scale",
    "label": "Less",
    "blurb": "Ryan Cuff: less is more — a 1.04 scale is the whole interaction.",
    "style_note": "transform:scale(1.04) on hover, that's the bit.",
    "marker": "--x50-micro-scale",
    "kind": "micro-scale",
    "fill": "#171717",
    "ink": "#fafafa",
    "accent": "#737373",
    "states": "default, hover, focus-visible, active, disabled",
    "keywords": [
      "micro scale",
      "less",
      "micro-scale",
      "ryancuff_",
      "underrated",
      "twitter button",
      "x.com showcase",
      "hover effect",
      "css button",
      "microinteraction",
      "x50-micro-scale",
      "transform:scale(1.04) on hover, that's t"
    ]
  }
];
export const TWITTER_50_LAST_PRIOR = "dust-premium";
