export const buttons = [
  {
    "title": "Information-Architecture Menu",
    "buttonLabel": "Menu navigation",
    "category": "Navigation/Menu",
    "visualTrait": "Icon-led navigation control presented as a structured information-architecture menu.",
    "sourceName": "The Baker Center",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/navigation-menu-the-baker-center",
    "imageUrl": "",
    "captureHint": "Crop the featured Navigation Menu image at the top of the Awwwards element page.",
    "tags": [
      "navigation",
      "menu",
      "icons",
      "information-architecture"
    ],
    "batch": "awwwards-live",
    "index": 1,
    "id": "001-information-architecture-menu"
  },
  {
    "title": "Foundation Menu Control",
    "buttonLabel": "Menu",
    "category": "Navigation/Menu",
    "visualTrait": "Menu treatment paired with a homepage scroll-navigation system and gallery-oriented layout.",
    "sourceName": "Analogue Foundation",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/menu-analogue-foundation",
    "imageUrl": "",
    "captureHint": "Crop the primary Menu image, then optionally capture its homepage scroll-navigation companion.",
    "tags": [
      "menu",
      "navigation",
      "gallery",
      "scroll"
    ],
    "batch": "awwwards-live",
    "index": 2,
    "id": "002-foundation-menu-control"
  },
  {
    "title": "Animated Producer Navigation",
    "buttonLabel": "Menu navigation",
    "category": "Navigation/Menu",
    "visualTrait": "Animated header menu/navigation treatment built around interactive producer tags.",
    "sourceName": "Producer Tags by Sara Cajner",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/menu-navigation-producer-tags-by-sara-cajner",
    "imageUrl": "",
    "captureHint": "Capture the featured menu-navigation media near the element title.",
    "tags": [
      "menu",
      "navigation",
      "header",
      "animation"
    ],
    "batch": "awwwards-live",
    "index": 3,
    "id": "003-animated-producer-navigation"
  },
  {
    "title": "Minimal Motion Button",
    "buttonLabel": "Button animation",
    "category": "Experimental/Motion",
    "visualTrait": "Minimal button treatment whose defining feature is an animated interaction rather than decorative chrome.",
    "sourceName": "Form Studio",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/button-animation-form-studio",
    "imageUrl": "",
    "captureHint": "Crop the Button Animation image at the top of the element page.",
    "tags": [
      "button",
      "minimal",
      "animation",
      "portfolio"
    ],
    "batch": "awwwards-live",
    "index": 4,
    "id": "004-minimal-motion-button"
  },
  {
    "title": "Portfolio Contact Motion CTA",
    "buttonLabel": "Contact",
    "category": "Experimental/Motion",
    "visualTrait": "Contact CTA designed as a motion-driven interactive button.",
    "sourceName": "Ritvik's Portfolio",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/contact-button-ritviks-portfolio",
    "imageUrl": "",
    "captureHint": "Capture the featured Contact button treatment near the page title.",
    "tags": [
      "button",
      "cta",
      "contact",
      "motion"
    ],
    "batch": "awwwards-live",
    "index": 5,
    "id": "005-portfolio-contact-motion-cta"
  },
  {
    "title": "3D Hover CTA",
    "buttonLabel": "CTA",
    "category": "3D/Physical",
    "visualTrait": "CTA using 3D presentation, GSAP-driven type, and hover animation.",
    "sourceName": "Double Play",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/cta-double-play",
    "imageUrl": "",
    "captureHint": "Crop the CTA image at the top of the Awwwards element page.",
    "tags": [
      "cta",
      "3d",
      "gsap",
      "hover"
    ],
    "batch": "awwwards-live",
    "index": 6,
    "id": "006-3d-hover-cta"
  },
  {
    "title": "Agency Interactive Navigation",
    "buttonLabel": "Site navigation",
    "category": "Navigation/Menu",
    "visualTrait": "Interactive navigation system integrated with the agency menu and services exploration.",
    "sourceName": "Fourmeta Agency",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/interactive-site-navigation-fourmeta-agency",
    "imageUrl": "",
    "captureHint": "Capture the featured interactive navigation and its menu animation media.",
    "tags": [
      "navigation",
      "menu",
      "services",
      "agency"
    ],
    "batch": "awwwards-live",
    "index": 7,
    "id": "007-agency-interactive-navigation"
  },
  {
    "title": "Arrow Navigation Buttons",
    "buttonLabel": "Arrow controls",
    "category": "Icon",
    "visualTrait": "Navigation controls use arrow-button affordances rather than text-only links.",
    "sourceName": "CreativeSideJaz",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/navigation-buttons-creativesidejaz",
    "imageUrl": "",
    "captureHint": "Crop either of the two featured navigation-button images near the page title.",
    "tags": [
      "navigation",
      "arrows",
      "buttons",
      "portfolio"
    ],
    "batch": "awwwards-live",
    "index": 8,
    "id": "008-arrow-navigation-buttons"
  },
  {
    "title": "Typographic Disrupt Menu",
    "buttonLabel": "Menu navigation",
    "category": "Navigation/Menu",
    "visualTrait": "Typography-forward animated menu navigation with a disruptive full-screen feel.",
    "sourceName": "Menu Inspiration",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/menu-navigation-disrupt",
    "imageUrl": "",
    "captureHint": "Capture the menu-navigation media at the top of the element page.",
    "tags": [
      "menu",
      "navigation",
      "typography",
      "animation"
    ],
    "batch": "awwwards-live",
    "index": 9,
    "id": "009-typographic-disrupt-menu"
  },
  {
    "title": "Animated Category Selector",
    "buttonLabel": "Category navigation",
    "category": "Toggle/Segmented",
    "visualTrait": "Category-navigation controls use transitions and animation as part of the selection state.",
    "sourceName": "Kultiveret",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/category-navigation-kultiveret",
    "imageUrl": "",
    "captureHint": "Crop the featured Category Navigation image or the desktop category state.",
    "tags": [
      "category",
      "navigation",
      "menu",
      "transition"
    ],
    "batch": "awwwards-live",
    "index": 10,
    "id": "010-animated-category-selector"
  },
  {
    "title": "Report Download Interaction",
    "buttonLabel": "Download",
    "category": "Secondary/Ghost",
    "visualTrait": "Download action is treated as an interaction-led editorial CTA rather than a generic utility link.",
    "sourceName": "ART+TECH Report 2023",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/download-button-interaction-art-tech-report-2023",
    "imageUrl": "",
    "captureHint": "Capture the Download Button Interaction featured media at the top of the page.",
    "tags": [
      "download",
      "cta",
      "editorial",
      "interaction"
    ],
    "batch": "awwwards-live",
    "index": 11,
    "id": "011-report-download-interaction"
  },
  {
    "title": "APF Hover Button",
    "buttonLabel": "Button hover",
    "category": "Experimental/Motion",
    "visualTrait": "Button uses an explicit hover-state animation, with related ripple-gradient treatment documented on the page.",
    "sourceName": "APF",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/button-hover-apf",
    "imageUrl": "",
    "captureHint": "Crop the main Button Hover visual and, if visible, its hover state.",
    "tags": [
      "button",
      "hover",
      "animation",
      "gradient"
    ],
    "batch": "awwwards-live",
    "index": 12,
    "id": "012-apf-hover-button"
  },
  {
    "title": "Product 3D CTA",
    "buttonLabel": "CTA",
    "category": "3D/Physical",
    "visualTrait": "Product-experience CTA shown alongside 3D product presentation and technical-detail content.",
    "sourceName": "HEAVN One",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/cta-heavn-one",
    "imageUrl": "",
    "captureHint": "Crop the CTA image at the top of the element page.",
    "tags": [
      "cta",
      "product",
      "3d",
      "commerce"
    ],
    "batch": "awwwards-live",
    "index": 13,
    "id": "013-product-3d-cta"
  },
  {
    "title": "Studio DOT Hover Control",
    "buttonLabel": "Button hover animation",
    "category": "Experimental/Motion",
    "visualTrait": "Studio button treatment documented as a motion-first hover interaction in a WebGL/GSAP portfolio.",
    "sourceName": "Studio DOT",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/slider-drag-and-drop-with-distortion-studio-dot-2",
    "imageUrl": "",
    "captureHint": "Capture the Button hover animation media within the Studio DOT element set.",
    "tags": [
      "button",
      "hover",
      "gsap",
      "webgl"
    ],
    "batch": "awwwards-live",
    "index": 14,
    "id": "014-studio-dot-hover-control"
  },
  {
    "title": "Immersive 3D Add-to-Cart",
    "buttonLabel": "Add to Cart",
    "category": "Commerce",
    "visualTrait": "Shopping action lives inside a 3D immersive product experience with cart and wishlist states.",
    "sourceName": "DIGITRON - 3D IMMERSIVE SITE",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/easy-search-and-navigation-digitron-3d-immersive-site",
    "imageUrl": "",
    "captureHint": "Capture the Add to Cart and Wishlist media in the linked element collection.",
    "tags": [
      "ecommerce",
      "add-to-cart",
      "3d",
      "wishlist"
    ],
    "batch": "awwwards-live",
    "index": 15,
    "id": "015-immersive-3d-add-to-cart"
  },
  {
    "title": "Impossible Toggle",
    "buttonLabel": "Impossible Toggle",
    "category": "Toggle/Segmented",
    "visualTrait": "A deliberately playful toggle appears alongside a documented standalone Button in an offset card system.",
    "sourceName": "Wondermake",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/navigation-cards-wondermake",
    "imageUrl": "",
    "captureHint": "Capture the Impossible Toggle or Button media in the Wondermake element list.",
    "tags": [
      "toggle",
      "button",
      "cards",
      "bento"
    ],
    "batch": "awwwards-live",
    "index": 16,
    "id": "016-impossible-toggle"
  },
  {
    "title": "Mobile Menu Transition",
    "buttonLabel": "Menu",
    "category": "Navigation/Menu",
    "visualTrait": "Mobile menu control is defined by a smooth animated transition and hover-linked navigation behavior.",
    "sourceName": "Andrey Mitko — Portfolio",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/smooth-scrolling-andrey-mitko-portfolio",
    "imageUrl": "",
    "captureHint": "Crop the featured Mobile Menu Transition media at the top of the page.",
    "tags": [
      "mobile",
      "menu",
      "transition",
      "animation"
    ],
    "batch": "awwwards-live",
    "index": 17,
    "id": "017-mobile-menu-transition"
  },
  {
    "title": "Cart Confirmation Message",
    "buttonLabel": "Add to cart",
    "category": "Accessibility/State",
    "visualTrait": "Commerce action is paired with an explicit add-to-cart confirmation/message state.",
    "sourceName": "Anti",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/thumbnail-anti",
    "imageUrl": "",
    "captureHint": "Capture the Anti - Add to cart message element from the featured content section.",
    "tags": [
      "commerce",
      "add-to-cart",
      "confirmation",
      "state"
    ],
    "batch": "awwwards-live",
    "index": 18,
    "id": "018-cart-confirmation-message"
  },
  {
    "title": "Travel Filter Control",
    "buttonLabel": "Filter",
    "category": "Toggle/Segmented",
    "visualTrait": "Travel-discovery filter control used as a compact utility action within a minimal interface.",
    "sourceName": "Travelshift",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/inspiration/home-travelshift-2",
    "imageUrl": "",
    "captureHint": "Capture the Filter media referenced in the related element collection.",
    "tags": [
      "filter",
      "travel",
      "minimal",
      "utility"
    ],
    "batch": "awwwards-live",
    "index": 19,
    "id": "019-travel-filter-control"
  },
  {
    "title": "Agency Contact Button",
    "buttonLabel": "Contact",
    "category": "Primary CTA",
    "visualTrait": "High-contrast agency contact action documented as a dedicated contact-page element within a black-led palette.",
    "sourceName": "Habitat Creative Agency",
    "sourceSite": "Awwwards",
    "sourceUrl": "https://www.awwwards.com/sites/habitat-creative-agency",
    "imageUrl": "",
    "captureHint": "Capture the 'Contact - Habitat Creative Agency' element from the project page's Elements section.",
    "tags": [
      "contact",
      "agency",
      "cta",
      "minimal"
    ],
    "batch": "awwwards-live",
    "index": 20,
    "id": "020-agency-contact-button"
  },
  {
    "title": "Pink branded social button",
    "buttonLabel": "Dribbble",
    "category": "Social/Share",
    "visualTrait": "A branded pink Dribbble button treatment with layered dark and light pink color states.",
    "sourceName": "Dribbble Button — Berislav Kirin",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/767753-Dribbble-Button",
    "imageUrl": "https://cdn.dribbble.com/userupload/19199959/file/original-fe715775651e24123839c40e2545a46f.png?resize=752x&vertical=center",
    "captureHint": "Centered button artwork in the shot.",
    "tags": [
      "social",
      "branded",
      "pink",
      "button"
    ],
    "batch": "dribbble-shots",
    "index": 21,
    "id": "021-pink-branded-social-button"
  },
  {
    "title": "Metallic back control",
    "buttonLabel": "Back",
    "category": "Navigation/Menu",
    "visualTrait": "A compact grey back button with a dark arrow, beveled metallic surface, and subtle shadow.",
    "sourceName": "Back Button UI element — Alex Lauderdale",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/287407-Back-Button-UI-element",
    "imageUrl": "",
    "captureHint": "Large standalone back control in the artwork.",
    "tags": [
      "back",
      "navigation",
      "metallic",
      "bevel"
    ],
    "batch": "dribbble-shots",
    "index": 22,
    "id": "022-metallic-back-control"
  },
  {
    "title": "Alien long-finger action bar",
    "buttonLabel": "Alien control",
    "category": "Experimental/Motion",
    "visualTrait": "An unusually long blue sci-fi button designed as a touch target for fictional alien fingers.",
    "sourceName": "Alien secret messenger, Calculator and elements, Daily UI 004 — Sairengy 👽",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/5266042-Alien-secret-messenger-Calculator-and-elements-Daily-UI-004",
    "imageUrl": "https://cdn.dribbble.com/userupload/23538189/file/original-8ab8be805f41944a3202989450075c02.jpg?resize=752x&vertical=center",
    "captureHint": "Long horizontal blue controls among the messenger interface elements.",
    "tags": [
      "futuristic",
      "blue",
      "long",
      "experimental"
    ],
    "batch": "dribbble-shots",
    "index": 23,
    "id": "023-alien-long-finger-action-bar"
  },
  {
    "title": "Thumb-zone play control",
    "buttonLabel": "Play/Pause",
    "category": "Icon",
    "visualTrait": "A prominent teal playback icon button positioned at the right middle of a mobile music interface.",
    "sourceName": "Sonos Concept UI - GIF — Grady Wetherbee",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/4324961-Sonos-Concept-UI-GIF",
    "imageUrl": "https://cdn.dribbble.com/userupload/22715249/file/original-e0d0f015116d573d145932772dc7a31d.gif",
    "captureHint": "Right-middle playback control on the mobile screen.",
    "tags": [
      "music",
      "play",
      "mobile",
      "thumb-zone"
    ],
    "batch": "dribbble-shots",
    "index": 24,
    "id": "024-thumb-zone-play-control"
  },
  {
    "title": "C4D crypto toggle",
    "buttonLabel": "On / Off",
    "category": "3D/Physical",
    "visualTrait": "A dark dimensional switch button rendered with physical depth and a raised knob.",
    "sourceName": "3D Switch Button — Alex Arutuynov 🤘",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/21716348-3D-Switch-Button",
    "imageUrl": "",
    "captureHint": "Central 3D switch object.",
    "tags": [
      "3d",
      "toggle",
      "dark",
      "physical"
    ],
    "batch": "dribbble-shots",
    "index": 25,
    "id": "025-c4d-crypto-toggle"
  },
  {
    "title": "Hold-to-confirm action",
    "buttonLabel": "Hold to confirm",
    "category": "Destructive/Confirm",
    "visualTrait": "A dark blue-grey confirmation button that fills over a nearly two-second press.",
    "sourceName": "Press button to confirm — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/8445173-Press-button-to-confirm",
    "imageUrl": "https://cdn.dribbble.com/userupload/25390182/file/large-d8f1b1b64df0559e24374ef9700bc0e1.mp4",
    "captureHint": "Central confirmation button and its hold-progress state.",
    "tags": [
      "confirm",
      "hold",
      "progress",
      "safety"
    ],
    "batch": "dribbble-shots",
    "index": 26,
    "id": "026-hold-to-confirm-action"
  },
  {
    "title": "Cloud publish loader",
    "buttonLabel": "Publish",
    "category": "Submit/Conversion",
    "visualTrait": "A bright blue publish CTA that transitions into a cloud-upload loading state.",
    "sourceName": "Publish button animation — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/14420497-Publish-button-animation",
    "imageUrl": "https://cdn.dribbble.com/userupload/29242382/file/large-9b16a3223f8e1c234769188d3a48a12b.mp4",
    "captureHint": "Centered publish button animation.",
    "tags": [
      "publish",
      "loading",
      "cloud",
      "blue"
    ],
    "batch": "dribbble-shots",
    "index": 27,
    "id": "027-cloud-publish-loader"
  },
  {
    "title": "Mouse-reactive glow CTA",
    "buttonLabel": "Glow button",
    "category": "Experimental/Motion",
    "visualTrait": "A dark CTA with a luminous hover glow that follows or reacts to the pointer.",
    "sourceName": "Glow Button Hover — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/19860772-Glow-Button-Hover",
    "imageUrl": "",
    "captureHint": "Standalone glowing control in the center.",
    "tags": [
      "glow",
      "hover",
      "dark",
      "cta"
    ],
    "batch": "dribbble-shots",
    "index": 28,
    "id": "028-mouse-reactive-glow-cta"
  },
  {
    "title": "Rotating plus action",
    "buttonLabel": "Add",
    "category": "Icon",
    "visualTrait": "A saturated blue circular add button whose plus icon animates on hover.",
    "sourceName": "Add Button hover animation — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/5419580-Add-Button-hover-animation",
    "imageUrl": "https://cdn.dribbble.com/userupload/23697028/file/original-6c5297e489dbea119dc6e728f407200d.gif",
    "captureHint": "Circular plus button and transformed hover state.",
    "tags": [
      "add",
      "plus",
      "hover",
      "icon"
    ],
    "batch": "dribbble-shots",
    "index": 29,
    "id": "029-rotating-plus-action"
  },
  {
    "title": "Arrow-to-close morph",
    "buttonLabel": "Back / Close",
    "category": "Navigation/Menu",
    "visualTrait": "A purple and white icon control that morphs from a directional arrow into a close icon.",
    "sourceName": "Arrow animations — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/10060282-Arrow-animations",
    "imageUrl": "https://cdn.dribbble.com/userupload/26089758/file/large-4dac0efbd2321cee71dd0d38d8d2027c.mp4",
    "captureHint": "Arrow and close-icon transformation in the middle.",
    "tags": [
      "arrow",
      "close",
      "morph",
      "navigation"
    ],
    "batch": "dribbble-shots",
    "index": 30,
    "id": "030-arrow-to-close-morph"
  },
  {
    "title": "Particle transfer hover",
    "buttonLabel": "Download / Upload",
    "category": "Experimental/Motion",
    "visualTrait": "Paired dark controls use animated particles to express download and upload states.",
    "sourceName": "Download & upload hover effects — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/10738257-Download-upload-hover-effects",
    "imageUrl": "https://cdn.dribbble.com/userupload/26393557/file/large-c5a3fca21e471ba5d9225b2ce8362c51.mp4",
    "captureHint": "The two transfer buttons and animated particles.",
    "tags": [
      "download",
      "upload",
      "particles",
      "hover"
    ],
    "batch": "dribbble-shots",
    "index": 31,
    "id": "031-particle-transfer-hover"
  },
  {
    "title": "Bouncing upload CTA",
    "buttonLabel": "Upload",
    "category": "Submit/Conversion",
    "visualTrait": "A blue upload button with a bounce-based hover interaction and animated affordance.",
    "sourceName": "Upload button hover — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/10681619-Upload-button-hover",
    "imageUrl": "https://cdn.dribbble.com/userupload/26346887/file/large-25bced98086f230abd3b7886194aeeb9.mp4",
    "captureHint": "Centered upload control and its hover frame.",
    "tags": [
      "upload",
      "bounce",
      "hover",
      "blue"
    ],
    "batch": "dribbble-shots",
    "index": 32,
    "id": "032-bouncing-upload-cta"
  },
  {
    "title": "Split-surface hover CTA",
    "buttonLabel": "Button hover effects",
    "category": "Experimental/Motion",
    "visualTrait": "A blue button uses split surfaces and shifting text/icon motion for its hover treatment.",
    "sourceName": "Button Hover Effects #2 — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/8764233-Button-Hover-Effects-2",
    "imageUrl": "https://cdn.dribbble.com/userupload/25470575/file/large-23c286f61f4c5251090be1ab039baf6e.mp4",
    "captureHint": "Button variants displayed across the central panel.",
    "tags": [
      "hover",
      "split",
      "cta",
      "motion"
    ],
    "batch": "dribbble-shots",
    "index": 33,
    "id": "033-split-surface-hover-cta"
  },
  {
    "title": "Framer GitHub star",
    "buttonLabel": "Star",
    "category": "Social/Share",
    "visualTrait": "A dark rounded star action that turns into a bright dimensional yellow star treatment.",
    "sourceName": "Star Button — Edoardo Mercati for Framer",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/16455206-Star-Button",
    "imageUrl": "https://cdn.dribbble.com/userupload/33330194/file/large-ebc1b280b621e602133abf172fd036a1.mp4",
    "captureHint": "Star button in the central interaction sequence.",
    "tags": [
      "star",
      "github",
      "yellow",
      "3d"
    ],
    "batch": "dribbble-shots",
    "index": 34,
    "id": "034-framer-github-star"
  },
  {
    "title": "Fluid-wave upload status",
    "buttonLabel": "Upload",
    "category": "Accessibility/State",
    "visualTrait": "An upload CTA uses a moving wave fill to communicate progress and completion.",
    "sourceName": "Wavy Upload Button — Aaron Iker",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/18176691-Wavy-Upload-Button",
    "imageUrl": "",
    "captureHint": "Central upload button with animated wave state.",
    "tags": [
      "upload",
      "wave",
      "progress",
      "success"
    ],
    "batch": "dribbble-shots",
    "index": 35,
    "id": "035-fluid-wave-upload-status"
  },
  {
    "title": "System button matrix",
    "buttonLabel": "Multiple button variants",
    "category": "Accessibility/State",
    "visualTrait": "A light-and-dark mobile design-system board comparing primary, secondary, disabled, and icon button styles.",
    "sourceName": "Figma iOS & Android buttons mobile design system UI kit — Setproduct",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/17216914-Figma-iOS-Android-buttons-mobile-design-system-UI-kit",
    "imageUrl": "https://cdn.dribbble.com/userupload/34896051/file/original-c3b90cc4899f373838c21af4f726c32c.png?resize=752x&vertical=center",
    "captureHint": "Button specimen groups across the UI kit board.",
    "tags": [
      "design-system",
      "mobile",
      "states",
      "variants"
    ],
    "batch": "dribbble-shots",
    "index": 36,
    "id": "036-system-button-matrix"
  },
  {
    "title": "Daily UI compact button set",
    "buttonLabel": "Multiple button variants",
    "category": "Accessibility/State",
    "visualTrait": "A compact system-style collection of button sizes, colors, and icon combinations.",
    "sourceName": "Button UI 48px - Daily UI — Unityle",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/24058551-Button-UI-48px-Daily-UI",
    "imageUrl": "",
    "captureHint": "Button component grid in the shot.",
    "tags": [
      "ui-kit",
      "components",
      "states",
      "dailyui"
    ],
    "batch": "dribbble-shots",
    "index": 37,
    "id": "037-daily-ui-compact-button-set"
  },
  {
    "title": "Warm-orange soft button kit",
    "buttonLabel": "Multiple button variants",
    "category": "Primary CTA",
    "visualTrait": "A warm orange and charcoal button exploration with soft corners, shadows, and contrasting states.",
    "sourceName": "Buttons UI Design — Ildiko Gaspar",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/14207778-Buttons-UI-Design",
    "imageUrl": "https://cdn.dribbble.com/userupload/28728358/file/original-a203a6b4a1c3b4939c4b044d32588c99.png?resize=752x&vertical=center",
    "captureHint": "Button components displayed in the central board.",
    "tags": [
      "orange",
      "ui-kit",
      "rounded",
      "cta"
    ],
    "batch": "dribbble-shots",
    "index": 38,
    "id": "038-warm-orange-soft-button-kit"
  },
  {
    "title": "Gallery arrow hover",
    "buttonLabel": "Next",
    "category": "Navigation/Menu",
    "visualTrait": "An editorial gallery arrow button built around hover/focus motion for an interior-design lightbox.",
    "sourceName": "Gallery Interaction — Petr Knoll for OFF MENU",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/6550959-Gallery-Interaction",
    "imageUrl": "https://cdn.dribbble.com/userupload/42780883/file/still-e56b0574c0f89c4d452d3a0b2f136003.png?resize=400x300&vertical=center",
    "captureHint": "Arrow navigation controls over the gallery imagery.",
    "tags": [
      "gallery",
      "arrow",
      "hover",
      "editorial"
    ],
    "batch": "dribbble-shots",
    "index": 39,
    "id": "039-gallery-arrow-hover"
  },
  {
    "title": "Dimensional web action button",
    "buttonLabel": "Action button",
    "category": "3D/Physical",
    "visualTrait": "A standalone rendered button with exaggerated 3D depth and physical product-like material.",
    "sourceName": "3D button — Simona Pralea for Bookmark",
    "sourceSite": "Dribbble",
    "sourceUrl": "https://dribbble.com/shots/20575944-3D-button",
    "imageUrl": "",
    "captureHint": "Large 3D button object in the center.",
    "tags": [
      "3d",
      "physical",
      "webflow",
      "experimental"
    ],
    "batch": "dribbble-shots",
    "index": 40,
    "id": "040-dimensional-web-action-button"
  },
  {
    "title": "Glass fashion store action",
    "buttonLabel": "Store action (label not exposed)",
    "category": "Commerce",
    "visualTrait": "Translucent glassmorphism-style store control within a fashion ecommerce interface.",
    "sourceName": "Ecommerce web UI UX - Glass morphism — Anupam Ghosh",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/115620643/Ecommerce-web-UI-UX-Glass-morphism",
    "imageUrl": "",
    "captureHint": "Main fashion-store glassmorphism UI image.",
    "tags": [
      "glassmorphism",
      "fashion",
      "ecommerce",
      "store"
    ],
    "batch": "behance-projects",
    "index": 41,
    "id": "041-glass-fashion-store-action"
  },
  {
    "title": "Checkout payment confirmation",
    "buttonLabel": "Checkout/payment action (label not exposed)",
    "category": "Submit/Conversion",
    "visualTrait": "Purchase-flow confirmation control appearing across catalogue, checkout, and payment screens.",
    "sourceName": "E-commerce design — Anastasiya Makhnyova",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/165629643/E-commerce-design",
    "imageUrl": "",
    "captureHint": "Checkout Page and payment-flow images.",
    "tags": [
      "checkout",
      "payment",
      "ecommerce",
      "conversion"
    ],
    "batch": "behance-projects",
    "index": 42,
    "id": "042-checkout-payment-confirmation"
  },
  {
    "title": "Dark editorial brutalist CTA",
    "buttonLabel": "Agency conversion action (label not exposed)",
    "category": "Primary CTA",
    "visualTrait": "Hard-edged action treatment in a dark editorial brutalist agency landing page.",
    "sourceName": "Nova Creative Agency | Brutalist Web Design | UI/UX — Danylo Simchuk",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/247507649/Nova-Creative-Agency-Brutalist-Web-Design-UIUX",
    "imageUrl": "",
    "captureHint": "Embedded project video / hero sequence.",
    "tags": [
      "brutalist",
      "dark",
      "editorial",
      "agency"
    ],
    "batch": "behance-projects",
    "index": 43,
    "id": "043-dark-editorial-brutalist-cta"
  },
  {
    "title": "Soft-pink playful mobile action",
    "buttonLabel": "Mobile flow action (label not exposed)",
    "category": "Primary CTA",
    "visualTrait": "Friendly touch target in a playful, soft light-pink mobile interface with rounded visual language.",
    "sourceName": "Mobile App UI/UX Design — Angelina Tkachenko",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/240707331/Mobile-App-UIUX-Design",
    "imageUrl": "",
    "captureHint": "Interactive prototype and mobile-flow screen set.",
    "tags": [
      "playful",
      "mobile",
      "pink",
      "onboarding"
    ],
    "batch": "behance-projects",
    "index": 44,
    "id": "044-soft-pink-playful-mobile-action"
  },
  {
    "title": "Blue-orange brutalist navigation",
    "buttonLabel": "Navigation/action (label not exposed)",
    "category": "Navigation/Menu",
    "visualTrait": "High-contrast blue-and-orange control language in an energetic brutalist agency website.",
    "sourceName": "Digital agency. Brutalism. Website design. — Oleksandra Mykhailenko",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/200574737/Digital-agency-Brutalism-Website-design",
    "imageUrl": "",
    "captureHint": "Main Hunter agency website composition.",
    "tags": [
      "brutalist",
      "blue",
      "orange",
      "navigation"
    ],
    "batch": "behance-projects",
    "index": 45,
    "id": "045-blue-orange-brutalist-navigation"
  },
  {
    "title": "Purple 3D music control",
    "buttonLabel": "Player/action control (label not exposed)",
    "category": "3D/Physical",
    "visualTrait": "Dimensional purple interaction control in a Beats/headphones music app concept.",
    "sourceName": "3D Mobile App UI Interaction — Olumide Olaiya",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/120794399/3D-Mobile-App-UI-Interaction",
    "imageUrl": "",
    "captureHint": "Main 3D mobile interaction image/video.",
    "tags": [
      "3d",
      "music",
      "purple",
      "mobile"
    ],
    "batch": "behance-projects",
    "index": 46,
    "id": "046-purple-3d-music-control"
  },
  {
    "title": "Glass bank-card button",
    "buttonLabel": "Banking action (label not exposed)",
    "category": "Primary CTA",
    "visualTrait": "Semi-transparent glassmorphism action control paired with bank-card UI.",
    "sourceName": "Glassmorphism - one of UI trend 2021 — Yuliia Herasymova",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/113174689/Glassmorphism-one-of-UI-trend-2021",
    "imageUrl": "",
    "captureHint": "Bank-card glass UI artwork in the project image.",
    "tags": [
      "glassmorphism",
      "banking",
      "card",
      "ui"
    ],
    "batch": "behance-projects",
    "index": 47,
    "id": "047-glass-bank-card-button"
  },
  {
    "title": "Game-like 3D mobile button",
    "buttonLabel": "Game action (label not exposed)",
    "category": "Experimental/Motion",
    "visualTrait": "Mobile game-interface action control designed alongside 3D modeling and micro-animation work.",
    "sourceName": "Dynamic Mobile UI — 3D Modeling & Micro-Animations — Filipe Paes Machado",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/247119561/Dynamic-Mobile-UI-3D-Modeling-Micro-Animations",
    "imageUrl": "",
    "captureHint": "First four mobile/game UI images in the project.",
    "tags": [
      "3d",
      "micro-animation",
      "game",
      "mobile"
    ],
    "batch": "behance-projects",
    "index": 48,
    "id": "048-game-like-3d-mobile-button"
  },
  {
    "title": "Dark-mode onboarding continuation",
    "buttonLabel": "Onboarding/login action (label not exposed)",
    "category": "Accessibility/State",
    "visualTrait": "High-contrast dark-mode mobile onboarding action designed across login and sign-up screens.",
    "sourceName": "Artdeco | Dark mode UX/UI Mobile App Onboarding — Ilaha Maharramova",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/202480435/Artdeco-Dark-mode-UXUI-Mobile-App-Onboarding",
    "imageUrl": "",
    "captureHint": "Onboarding, login, and sign-up screen sequence.",
    "tags": [
      "dark-mode",
      "onboarding",
      "login",
      "mobile"
    ],
    "batch": "behance-projects",
    "index": 49,
    "id": "049-dark-mode-onboarding-continuation"
  },
  {
    "title": "Binary state toggle reference",
    "buttonLabel": "On / Off",
    "category": "Toggle/Segmented",
    "visualTrait": "Switch-style binary state control accompanied by visual examples and interaction-state guidance.",
    "sourceName": "History Of Toggle + UI/UX Case Study + UI Samples — Ramulu Nelli",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/70302039/History-Of-Toggle-UIUX-Case-Study-UI-Samples",
    "imageUrl": "",
    "captureHint": "Design Samples section; the project includes numerous toggle examples.",
    "tags": [
      "toggle",
      "switch",
      "on-off",
      "states"
    ],
    "batch": "behance-projects",
    "index": 50,
    "id": "050-binary-state-toggle-reference"
  },
  {
    "title": "Magnetic green on-off switch",
    "buttonLabel": "On / Off",
    "category": "Toggle/Segmented",
    "visualTrait": "Vibrant green minimalist toggle with two circular elements that separate and align through a smooth magnetic-switch-like animation.",
    "sourceName": "UI/UX Design - On/Off Switch - Toggle — Thomas T.",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/214744437/UIUX-Design-OnOff-Switch-Toggle",
    "imageUrl": "",
    "captureHint": "Primary on/off switch concept image.",
    "tags": [
      "toggle",
      "green",
      "magnetic",
      "animation"
    ],
    "batch": "behance-projects",
    "index": 51,
    "id": "051-magnetic-green-on-off-switch"
  },
  {
    "title": "Glowing dark-mode app action",
    "buttonLabel": "App action (label not exposed)",
    "category": "Accessibility/State",
    "visualTrait": "Vivid, glowing action treatment against a dark mobile UI designed for Token of Me.",
    "sourceName": "Token of Me — Dark Mode UI/UX — Anry Marchen",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/170318591/Token-of-Me-Dark-Mode-UIUX",
    "imageUrl": "",
    "captureHint": "Dark-mode app screen set.",
    "tags": [
      "dark-mode",
      "glow",
      "mobile",
      "app"
    ],
    "batch": "behance-projects",
    "index": 52,
    "id": "052-glowing-dark-mode-app-action"
  },
  {
    "title": "Particle Burst Send",
    "buttonLabel": "Send",
    "category": "Experimental/Motion",
    "visualTrait": "A compact action button emits a playful burst of particles after activation.",
    "sourceName": "Particle Effects for Buttons",
    "sourceSite": "Codrops",
    "sourceUrl": "https://tympanus.net/Development/ParticleEffectsButtons/",
    "imageUrl": "",
    "captureHint": "Click Send, then capture the button and its particle burst against the dark demo canvas.",
    "tags": [
      "particles",
      "click",
      "send"
    ],
    "batch": "frontend-experiments",
    "index": 53,
    "id": "053-particle-burst-send"
  },
  {
    "title": "Magnetic Circle CTA",
    "buttonLabel": "Send",
    "category": "Experimental/Motion",
    "visualTrait": "A circular outlined CTA and inner text pull independently toward the cursor for a parallax magnetic effect.",
    "sourceName": "Magnetic Buttons inspired by Cuberto",
    "sourceSite": "Codrops",
    "sourceUrl": "https://tympanus.net/Development/MagneticButtons/index.html",
    "imageUrl": "",
    "captureHint": "Move the cursor near Send and capture the displaced circle, text, and shadow.",
    "tags": [
      "magnetic",
      "cursor",
      "parallax"
    ],
    "batch": "frontend-experiments",
    "index": 54,
    "id": "054-magnetic-circle-cta"
  },
  {
    "title": "SVG Noise Distortion",
    "buttonLabel": "Click me",
    "category": "Experimental/Motion",
    "visualTrait": "A set of minimalist button treatments warp and smear through SVG filter distortion on interaction.",
    "sourceName": "Distorted Button Effects Using SVG Filters",
    "sourceSite": "Codrops",
    "sourceUrl": "https://tympanus.net/Development/DistortedButtonEffects/?default-tab=result&height=316&theme-id=0",
    "imageUrl": "",
    "captureHint": "Hover or click one numbered Click me variation and crop a single distorted state.",
    "tags": [
      "svg",
      "distortion",
      "experimental"
    ],
    "batch": "frontend-experiments",
    "index": 55,
    "id": "055-svg-noise-distortion"
  },
  {
    "title": "Gooey Blob Hover",
    "buttonLabel": "Hover me!",
    "category": "Experimental/Motion",
    "visualTrait": "A light pill button grows two rounded blobs through an SVG goo filter over a charcoal background.",
    "sourceName": "Gooey button hover effect with SVG filters & CSS by Ines",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/ines/pen/oeZdYv",
    "imageUrl": "",
    "captureHint": "Hover the centered button and crop the expanded blob silhouette.",
    "tags": [
      "gooey",
      "svg-filter",
      "blob"
    ],
    "batch": "frontend-experiments",
    "index": 56,
    "id": "056-gooey-blob-hover"
  },
  {
    "title": "Hold-to-Publish Confirmation",
    "buttonLabel": "Publish / Sure? / Public",
    "category": "Destructive/Confirm",
    "visualTrait": "A hold interaction cycles text while a circular SVG progress ring completes into a checkmark.",
    "sourceName": "(v2) Button - Hold to confirm (Accessible) by Aaron Iker",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/aaroniker/pen/BayaBpV",
    "imageUrl": "",
    "captureHint": "Press and hold until the ring is mid-progress or the final tick is visible.",
    "tags": [
      "hold",
      "progress",
      "confirmation"
    ],
    "batch": "frontend-experiments",
    "index": 57,
    "id": "057-hold-to-publish-confirmation"
  },
  {
    "title": "Glass Morphism Action",
    "buttonLabel": "Glass Effect",
    "category": "Primary CTA",
    "visualTrait": "A translucent frosted-glass button is presented as one of several interactive visual button recipes.",
    "sourceName": "Interactive Buttons Collection",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/pixelmasters/pen/KwVvqVO",
    "imageUrl": "",
    "captureHint": "Crop the Glass Morphism card tightly around its button and label.",
    "tags": [
      "glass",
      "frosted",
      "collection"
    ],
    "batch": "frontend-experiments",
    "index": 58,
    "id": "058-glass-morphism-action"
  },
  {
    "title": "Animated Icon Circle",
    "buttonLabel": "Arrow icon",
    "category": "Icon",
    "visualTrait": "An icon-only circular control uses layered pseudo-elements and motion to animate the directional glyph.",
    "sourceName": "Part 04, 05, 06: Animated Buttons - Mastering CSS Animations by CodyHouse",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/codyhouse/pen/gOLpXLr",
    "imageUrl": "",
    "captureHint": "Hover the round icon-button variant and capture both its circle and moving icon.",
    "tags": [
      "icon",
      "circle",
      "microinteraction"
    ],
    "batch": "frontend-experiments",
    "index": 59,
    "id": "059-animated-icon-circle"
  },
  {
    "title": "Running Neon Border",
    "buttonLabel": "Hover Here!",
    "category": "Experimental/Motion",
    "visualTrait": "A magenta rectangular CTA has four golden light streaks continuously travelling around its edges.",
    "sourceName": "Creative Button Animation Effects | Only Using HTML & CSS by Ahmad Emran",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/ahmadbassamemran/pen/PMqayW",
    "imageUrl": "",
    "captureHint": "Capture the button at a moment where multiple animated border streaks are visible.",
    "tags": [
      "neon",
      "border",
      "animation"
    ],
    "batch": "frontend-experiments",
    "index": 60,
    "id": "060-running-neon-border"
  },
  {
    "title": "Hold-to-Delete Fill",
    "buttonLabel": "Close icon",
    "category": "Destructive/Confirm",
    "visualTrait": "A small red destructive icon control fills from its center while it is held before triggering deletion.",
    "sourceName": "Hold to delete button (bootstrap) by yspreen",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/yspreen/pen/gxPmGY",
    "imageUrl": "",
    "captureHint": "Press and hold the red X control, then crop it at roughly half-filled progress.",
    "tags": [
      "delete",
      "hold",
      "progress"
    ],
    "batch": "frontend-experiments",
    "index": 61,
    "id": "061-hold-to-delete-fill"
  },
  {
    "title": "Hold-to-Wave Trigger",
    "buttonLabel": "Hold to Wave",
    "category": "Experimental/Motion",
    "visualTrait": "A plain hold button activates a dynamic SVG sound-wave field below it.",
    "sourceName": "Squingly Wave Machine by Giedr-Ju",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/Giedr-Ju/pen/azOGbrd",
    "imageUrl": "",
    "captureHint": "Press and hold, capturing the button together with the activated wave lines.",
    "tags": [
      "hold",
      "wave",
      "svg"
    ],
    "batch": "frontend-experiments",
    "index": 62,
    "id": "062-hold-to-wave-trigger"
  },
  {
    "title": "Angled Red 3D Disc",
    "buttonLabel": "GET A CONSULTATION",
    "category": "3D/Physical",
    "visualTrait": "A large red circular CTA is rotated in 3D with a thick offset base and glossy inset highlights.",
    "sourceName": "Red Round 3D Button (CSS only) by Oleksandr Shepa",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/Oleksandrshepa/pen/ZEJappK",
    "imageUrl": "",
    "captureHint": "Capture the entire red disc and its deep lower-right base shadow.",
    "tags": [
      "3d",
      "round",
      "physical"
    ],
    "batch": "frontend-experiments",
    "index": 63,
    "id": "063-angled-red-3d-disc"
  },
  {
    "title": "Yellow Skewed Push Button",
    "buttonLabel": "3D Button",
    "category": "3D/Physical",
    "visualTrait": "A bright yellow uppercase button uses a hard diagonal dark shadow to create an arcade-like press effect.",
    "sourceName": "3D Button by screenthink",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/screenthink/pen/ZeOyjP",
    "imageUrl": "",
    "captureHint": "Hover or press the centered yellow button and include its offset brown shadow.",
    "tags": [
      "3d",
      "shadow",
      "typography"
    ],
    "batch": "frontend-experiments",
    "index": 64,
    "id": "064-yellow-skewed-push-button"
  },
  {
    "title": "Blue Arcade Press",
    "buttonLabel": "click me!",
    "category": "3D/Physical",
    "visualTrait": "A rounded cyan button drops its solid eight-pixel base when pressed for a simple tactile response.",
    "sourceName": "Simple 3D Button CSS only by tomizius-the-sasster",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/tomizius-the-sasster/pen/maKqZM",
    "imageUrl": "",
    "captureHint": "Capture before and during active press to show the lowered state.",
    "tags": [
      "3d",
      "press",
      "arcade"
    ],
    "batch": "frontend-experiments",
    "index": 65,
    "id": "065-blue-arcade-press"
  },
  {
    "title": "SVG Click Ripple",
    "buttonLabel": "Click for Ripple",
    "category": "Experimental/Motion",
    "visualTrait": "A broad material-pink button launches a scalable SVG circle ripple exactly from the click point.",
    "sourceName": "A Pen by Ludvig Lindblom",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/ludviglindblom/pen/VwadqPj",
    "imageUrl": "",
    "captureHint": "Click off-center and capture the expanding darker ripple inside the button bounds.",
    "tags": [
      "ripple",
      "svg",
      "material"
    ],
    "batch": "frontend-experiments",
    "index": 66,
    "id": "066-svg-click-ripple"
  },
  {
    "title": "Rotating Liquid Pill",
    "buttonLabel": "Hover Me",
    "category": "Experimental/Motion",
    "visualTrait": "A cyan rounded pill contains a large translucent rotating liquid surface and shifts neon-green on hover.",
    "sourceName": "Liquid Button Hover Effect (CSS Only, Responsive) by Ahmod Musa",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/Ahmod-Musa/pen/empOpJv",
    "imageUrl": "",
    "captureHint": "Hover the pill and capture the rotating liquid texture through its clipped rounded edge.",
    "tags": [
      "liquid",
      "pill",
      "hover"
    ],
    "batch": "frontend-experiments",
    "index": 67,
    "id": "067-rotating-liquid-pill"
  },
  {
    "title": "Orange Isometric Press",
    "buttonLabel": "3D Button 1",
    "category": "3D/Physical",
    "visualTrait": "An orange rectangular button has faux isometric side faces and a hard down-left press translation.",
    "sourceName": "CSS 3D Button 1 by mudontire",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/mudontire/pen/aeJQqB",
    "imageUrl": "",
    "captureHint": "Capture both the resting faux side faces and the pressed lower position.",
    "tags": [
      "isometric",
      "3d",
      "press"
    ],
    "batch": "frontend-experiments",
    "index": 68,
    "id": "068-orange-isometric-press"
  },
  {
    "title": "Material Ink Ripple",
    "buttonLabel": "Material Design Ripple Button",
    "category": "Primary CTA",
    "visualTrait": "A flat blue text CTA uses a contained circular ink ripple layer in a classic Material-style interaction.",
    "sourceName": "Ripple.js - Material Design Ripple Buttons by william-wise",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/william-wise/pen/GNOqJO",
    "imageUrl": "",
    "captureHint": "Click near a corner to show the expanding darker blue circular ripple.",
    "tags": [
      "ripple",
      "material",
      "click"
    ],
    "batch": "frontend-experiments",
    "index": 69,
    "id": "069-material-ink-ripple"
  },
  {
    "title": "Tilted Social Blocks",
    "buttonLabel": "instagram",
    "category": "Social/Share",
    "visualTrait": "A white social button is heavily rotated and skewed with extruded-looking side faces and an icon-plus-label layout.",
    "sourceName": "Fake 3D Button Only With CSS Final Version by evolab",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/evolab/pen/WNmZJoE",
    "imageUrl": "",
    "captureHint": "Crop one social button with its icon, text, skewed geometry, and shadow fully visible.",
    "tags": [
      "social",
      "3d",
      "skewed"
    ],
    "batch": "frontend-experiments",
    "index": 70,
    "id": "070-tilted-social-blocks"
  },
  {
    "title": "3D Loading State",
    "buttonLabel": "Loading…",
    "category": "Accessibility/State",
    "visualTrait": "A cyan depth button swaps into a disabled loading state with a compact spinning ring and visible focus treatment.",
    "sourceName": "3D Buttons & Microinteractions – Pure CSS Depth + Press States by adiadila123",
    "sourceSite": "CodePen",
    "sourceUrl": "https://codepen.io/adiadila123/pen/XJXPdJG",
    "imageUrl": "",
    "captureHint": "Capture the Loading state before it changes to Loaded, including spinner and layered depth shadow.",
    "tags": [
      "loading",
      "3d",
      "state"
    ],
    "batch": "frontend-experiments",
    "index": 71,
    "id": "071-3d-loading-state"
  },
  {
    "title": "Progress Morph CTA",
    "buttonLabel": "Submit",
    "category": "Submit/Conversion",
    "visualTrait": "A dedicated demo collection turns conventional submit controls into visual progress indicators and completion states.",
    "sourceName": "Progress Button Styles",
    "sourceSite": "Codrops",
    "sourceUrl": "https://tympanus.net/Development/ProgressButtonStyles/",
    "imageUrl": "",
    "captureHint": "Click a Submit variant, then crop it midway through its progress or final success transformation.",
    "tags": [
      "progress",
      "submit",
      "morph"
    ],
    "batch": "frontend-experiments",
    "index": 72,
    "id": "072-progress-morph-cta"
  },
  {
    "title": "Filled primary action",
    "buttonLabel": "Contained",
    "category": "Primary CTA",
    "visualTrait": "Elevated filled rectangle gives the main in-app action the highest visual emphasis.",
    "sourceName": "Material UI Button",
    "sourceSite": "Material UI",
    "sourceUrl": "https://mui.com/material-ui/react-button/",
    "imageUrl": "",
    "captureHint": "Crop the Contained button in the Basic button example.",
    "tags": [
      "contained",
      "elevated",
      "primary"
    ],
    "batch": "design-systems",
    "index": 73,
    "id": "073-filled-primary-action"
  },
  {
    "title": "Capsule primary button",
    "buttonLabel": "Primary",
    "category": "Primary CTA",
    "visualTrait": "A highly rounded capsule form is recommended for standalone Apple-platform actions.",
    "sourceName": "Apple Human Interface Guidelines Buttons",
    "sourceSite": "Apple Developer",
    "sourceUrl": "https://developer.apple.com/design/human-interface-guidelines/buttons?changes=latest_1",
    "imageUrl": "",
    "captureHint": "Crop the capsule-shaped primary button from the watchOS illustration.",
    "tags": [
      "capsule",
      "apple",
      "primary"
    ],
    "batch": "design-systems",
    "index": 74,
    "id": "074-capsule-primary-button"
  },
  {
    "title": "Negative outlined action",
    "buttonLabel": "Action",
    "category": "Destructive/Confirm",
    "visualTrait": "A red outline signals a destructive or consequential action at a restrained emphasis level.",
    "sourceName": "Spectrum Button",
    "sourceSite": "Adobe Spectrum",
    "sourceUrl": "https://spectrum.adobe.com/page/button/",
    "imageUrl": "",
    "captureHint": "Crop the Negative variant outline example.",
    "tags": [
      "negative",
      "destructive",
      "outline"
    ],
    "batch": "design-systems",
    "index": 75,
    "id": "075-negative-outlined-action"
  },
  {
    "title": "Split action button",
    "buttonLabel": "New message",
    "category": "Navigation/Menu",
    "visualTrait": "A dominant labeled action is attached to a separate menu trigger for closely related alternatives.",
    "sourceName": "Fluent 2 Button",
    "sourceSite": "Microsoft Fluent 2",
    "sourceUrl": "https://fluent2.microsoft.design/components/web/react/core/button/usage",
    "imageUrl": "",
    "captureHint": "Crop the Split button type preview.",
    "tags": [
      "split",
      "menu",
      "compound-action"
    ],
    "batch": "design-systems",
    "index": 76,
    "id": "076-split-action-button"
  },
  {
    "title": "Danger confirmation button",
    "buttonLabel": "Danger",
    "category": "Destructive/Confirm",
    "visualTrait": "A distinct danger variant is reserved for destructive actions that generally require confirmation.",
    "sourceName": "Primer Button",
    "sourceSite": "GitHub Primer",
    "sourceUrl": "https://primer.style/product/components/button/",
    "imageUrl": "",
    "captureHint": "Crop the Danger button in Style variants.",
    "tags": [
      "danger",
      "github",
      "destructive"
    ],
    "batch": "design-systems",
    "index": 77,
    "id": "077-danger-confirmation-button"
  },
  {
    "title": "Icon and count reaction",
    "buttonLabel": "Things",
    "category": "Social/Share",
    "visualTrait": "A button combines a concise action label with a numeric count for social or status feedback.",
    "sourceName": "Pajamas Button",
    "sourceSite": "GitLab Pajamas",
    "sourceUrl": "https://design.gitlab.com/components/button/",
    "imageUrl": "",
    "captureHint": "Crop the Basic count button example.",
    "tags": [
      "count",
      "reaction",
      "status"
    ],
    "batch": "design-systems",
    "index": 78,
    "id": "078-icon-and-count-reaction"
  },
  {
    "title": "Government start-page CTA",
    "buttonLabel": "Start now",
    "category": "Submit/Conversion",
    "visualTrait": "A large, left-aligned service-entry action uses direct sentence-case language.",
    "sourceName": "GOV.UK Button",
    "sourceSite": "GOV.UK Design System",
    "sourceUrl": "https://design-system.service.gov.uk/components/button/",
    "imageUrl": "",
    "captureHint": "Crop the Start now start-button example.",
    "tags": [
      "government",
      "start",
      "service"
    ],
    "batch": "design-systems",
    "index": 79,
    "id": "079-government-start-page-cta"
  },
  {
    "title": "Accessible segmented progression",
    "buttonLabel": "Continue",
    "category": "Toggle/Segmented",
    "visualTrait": "A current filled button pairs with an outlined Back control in an explicitly responsive action group.",
    "sourceName": "USWDS Button group",
    "sourceSite": "U.S. Web Design System",
    "sourceUrl": "https://designsystem.digital.gov/components/button-group/",
    "imageUrl": "",
    "captureHint": "Crop the default button group showing Back and Continue.",
    "tags": [
      "segmented",
      "progression",
      "government"
    ],
    "batch": "design-systems",
    "index": 80,
    "id": "080-accessible-segmented-progression"
  },
  {
    "title": "Dark Product System CTA Pair",
    "buttonLabel": "Get started / Contact sales",
    "category": "Primary CTA",
    "visualTrait": "High-contrast paired calls to action on Linear’s dark, highly minimal product-marketing layout.",
    "sourceName": "Linear homepage",
    "sourceSite": "linear.app",
    "sourceUrl": "https://linear.app/homepage",
    "imageUrl": "",
    "captureHint": "Crop the top navigation or the final “Built for the future” CTA block.",
    "tags": [
      "saas",
      "dark",
      "minimal",
      "conversion"
    ],
    "batch": "curated-product-sites",
    "index": 81,
    "id": "081-dark-product-system-cta-pair"
  },
  {
    "title": "Plan Card Start CTA",
    "buttonLabel": "Get started",
    "category": "Submit/Conversion",
    "visualTrait": "Repeated compact plan-selection CTAs create a clear conversion rhythm inside a restrained pricing grid.",
    "sourceName": "Linear pricing",
    "sourceSite": "linear.app",
    "sourceUrl": "https://linear.app/pricing",
    "imageUrl": "",
    "captureHint": "Crop any Free, Basic, or Business pricing card with its Get started action.",
    "tags": [
      "pricing",
      "saas",
      "conversion",
      "card"
    ],
    "batch": "curated-product-sites",
    "index": 82,
    "id": "082-plan-card-start-cta"
  },
  {
    "title": "Four-Action Product Nav",
    "buttonLabel": "Contact sales / Get started / Download / Open app",
    "category": "Navigation/Menu",
    "visualTrait": "A concise quartet of utility and conversion actions makes the navigation feel like a product command bar.",
    "sourceName": "Linear features",
    "sourceSite": "linear.app",
    "sourceUrl": "https://linear.app/features",
    "imageUrl": "",
    "captureHint": "Crop the header action cluster near the top of the features page.",
    "tags": [
      "navigation",
      "saas",
      "utility",
      "dark"
    ],
    "batch": "curated-product-sites",
    "index": 83,
    "id": "083-four-action-product-nav"
  },
  {
    "title": "Program Application Button",
    "buttonLabel": "Apply",
    "category": "Submit/Conversion",
    "visualTrait": "A single concise application action is isolated at the end of an eligibility-focused startup offer.",
    "sourceName": "Linear for Startups",
    "sourceSite": "linear.app",
    "sourceUrl": "https://linear.app/startups",
    "imageUrl": "",
    "captureHint": "Crop the Linear Startup Program eligibility panel and its Apply button.",
    "tags": [
      "application",
      "startup",
      "conversion",
      "minimal"
    ],
    "batch": "curated-product-sites",
    "index": 84,
    "id": "084-program-application-button"
  },
  {
    "title": "Platform Download Pill Set",
    "buttonLabel": "Download for Mac / Download for Windows (beta)",
    "category": "Primary CTA",
    "visualTrait": "Two adjacent OS-specific downloads turn a standard CTA into a clear platform-choice control.",
    "sourceName": "Raycast homepage",
    "sourceSite": "raycast.com",
    "sourceUrl": "https://www.raycast.com/",
    "imageUrl": "",
    "captureHint": "Crop the hero’s Mac and Windows download buttons, including the install-via-package-manager option.",
    "tags": [
      "download",
      "platform",
      "dark",
      "productivity"
    ],
    "batch": "curated-product-sites",
    "index": 85,
    "id": "085-platform-download-pill-set"
  },
  {
    "title": "Browser Download Choice",
    "buttonLabel": "Download Arc for Windows / Download Arc for Mac",
    "category": "Primary CTA",
    "visualTrait": "Platform-specific download buttons are repeated through a calm editorial browser landing page.",
    "sourceName": "Arc",
    "sourceSite": "arc.net",
    "sourceUrl": "https://arc.net/",
    "imageUrl": "",
    "captureHint": "Crop the main download buttons immediately under the Arc introduction.",
    "tags": [
      "download",
      "browser",
      "editorial",
      "platform"
    ],
    "batch": "curated-product-sites",
    "index": 86,
    "id": "086-browser-download-choice"
  },
  {
    "title": "Figma Hero Start Button",
    "buttonLabel": "Get started",
    "category": "Primary CTA",
    "visualTrait": "A solitary high-priority onboarding action sits against Figma’s expressive collaborative-canvas hero.",
    "sourceName": "Figma homepage",
    "sourceSite": "figma.com",
    "sourceUrl": "https://www.figma.com/",
    "imageUrl": "",
    "captureHint": "Crop the hero title and Get started control.",
    "tags": [
      "design-tool",
      "onboarding",
      "primary",
      "colorful"
    ],
    "batch": "curated-product-sites",
    "index": 87,
    "id": "087-figma-hero-start-button"
  },
  {
    "title": "Creative Mode Segmented Controls",
    "buttonLabel": "Design / Draw / Build / Publish / Promote / Jam / Present",
    "category": "Toggle/Segmented",
    "visualTrait": "A row of labeled mode buttons works as a playful segmented map of Figma’s product surface.",
    "sourceName": "Figma about",
    "sourceSite": "figma.com",
    "sourceUrl": "https://www.figma.com/about/",
    "imageUrl": "",
    "captureHint": "Crop the mode-button row below the Get started for free and Contact sales actions.",
    "tags": [
      "segmented",
      "design-tool",
      "navigation",
      "playful"
    ],
    "batch": "curated-product-sites",
    "index": 88,
    "id": "088-creative-mode-segmented-controls"
  },
  {
    "title": "Arrow Text CTA",
    "buttonLabel": "Learn more",
    "category": "Secondary/Ghost",
    "visualTrait": "Unboxed text links with arrow affordances keep the page’s visual focus on editorial imagery and content.",
    "sourceName": "Figma Sites",
    "sourceSite": "figma.com",
    "sourceUrl": "https://www.figma.com/sites/",
    "imageUrl": "",
    "captureHint": "Crop one product-feature row showing its Learn more arrow link.",
    "tags": [
      "text-link",
      "arrow",
      "editorial",
      "secondary"
    ],
    "batch": "curated-product-sites",
    "index": 89,
    "id": "089-arrow-text-cta"
  },
  {
    "title": "Balanced Dual Hero Actions",
    "buttonLabel": "Get started / Contact sales",
    "category": "Primary CTA",
    "visualTrait": "A direct primary-and-secondary pair supports self-serve adoption and enterprise sales in one hero.",
    "sourceName": "Figma Design",
    "sourceSite": "figma.com",
    "sourceUrl": "https://www.figma.com/design/",
    "imageUrl": "",
    "captureHint": "Crop the hero beneath “Made for the big picture.”",
    "tags": [
      "design-tool",
      "b2b",
      "dual-cta",
      "hero"
    ],
    "batch": "curated-product-sites",
    "index": 90,
    "id": "090-balanced-dual-hero-actions"
  },
  {
    "title": "AI-versus-Free CTA Split",
    "buttonLabel": "Start with AI / Start for free",
    "category": "Experimental/Motion",
    "visualTrait": "Competing entry points distinguish generative creation from the conventional free-start path.",
    "sourceName": "Framer homepage",
    "sourceSite": "framer.com",
    "sourceUrl": "https://www.framer.com/",
    "imageUrl": "",
    "captureHint": "Crop the homepage hero action pair under “Just publish it with Framer.”",
    "tags": [
      "ai",
      "website-builder",
      "dual-cta",
      "creative"
    ],
    "batch": "curated-product-sites",
    "index": 91,
    "id": "091-ai-versus-free-cta-split"
  },
  {
    "title": "Tiered Pricing Action Set",
    "buttonLabel": "Try for free / Start with Basic / Start with Pro / Request Trial",
    "category": "Submit/Conversion",
    "visualTrait": "Each pricing tier uses a differently worded action that mirrors its commitment level.",
    "sourceName": "Framer pricing",
    "sourceSite": "framer.com",
    "sourceUrl": "https://www.framer.com/pricing",
    "imageUrl": "",
    "captureHint": "Crop all four plan-card CTA buttons in one pricing-grid image.",
    "tags": [
      "pricing",
      "conversion",
      "saas",
      "card"
    ],
    "batch": "curated-product-sites",
    "index": 92,
    "id": "092-tiered-pricing-action-set"
  },
  {
    "title": "Talk-or-Start Hosting CTA",
    "buttonLabel": "Talk to our team / Start for free",
    "category": "Primary CTA",
    "visualTrait": "An enterprise conversation action and a self-serve action sit together above technical hosting content.",
    "sourceName": "Framer hosting",
    "sourceSite": "framer.com",
    "sourceUrl": "https://www.framer.com/hosting/",
    "imageUrl": "",
    "captureHint": "Crop the hero CTA pair below the hosting headline.",
    "tags": [
      "hosting",
      "b2b",
      "dual-cta",
      "enterprise"
    ],
    "batch": "curated-product-sites",
    "index": 93,
    "id": "093-talk-or-start-hosting-cta"
  },
  {
    "title": "Analytics Video Secondary",
    "buttonLabel": "Start for free / Watch video",
    "category": "Secondary/Ghost",
    "visualTrait": "A free-start conversion button is balanced with a lower-commitment video-preview action.",
    "sourceName": "Framer Analytics",
    "sourceSite": "framer.com",
    "sourceUrl": "https://www.framer.com/analytics",
    "imageUrl": "",
    "captureHint": "Crop the first action pair at the top of the Analytics page.",
    "tags": [
      "analytics",
      "video",
      "saas",
      "secondary"
    ],
    "batch": "curated-product-sites",
    "index": 94,
    "id": "094-analytics-video-secondary"
  },
  {
    "title": "Component-State Button Demo",
    "buttonLabel": "Get Started",
    "category": "Accessibility/State",
    "visualTrait": "The page explicitly displays a primary button and its hover state as a component-system example.",
    "sourceName": "Framer Design Pages",
    "sourceSite": "framer.com",
    "sourceUrl": "https://www.framer.com/features/navigation/",
    "imageUrl": "",
    "captureHint": "Crop the component specimen labeled “Button • Primary” and “Button • Hover.”",
    "tags": [
      "component",
      "hover",
      "design-system",
      "state"
    ],
    "batch": "curated-product-sites",
    "index": 95,
    "id": "095-component-state-button-demo"
  },
  {
    "title": "Free-or-Demo Workspace Pair",
    "buttonLabel": "Get Notion free / Request a demo",
    "category": "Primary CTA",
    "visualTrait": "A minimal enterprise SaaS pairing separates immediate signup from assisted evaluation.",
    "sourceName": "Notion product overview",
    "sourceSite": "notion.com",
    "sourceUrl": "https://www.notion.com/en-US/product/notion",
    "imageUrl": "",
    "captureHint": "Crop the hero action pair under “So... what is Notion?”",
    "tags": [
      "workspace",
      "b2b",
      "dual-cta",
      "minimal"
    ],
    "batch": "curated-product-sites",
    "index": 96,
    "id": "096-free-or-demo-workspace-pair"
  },
  {
    "title": "Demo Video Proof CTA",
    "buttonLabel": "Get Notion free / Watch demo video",
    "category": "Secondary/Ghost",
    "visualTrait": "A signup conversion button is paired with a video action for buyers who need product proof first.",
    "sourceName": "Notion Enterprise Search",
    "sourceSite": "notion.com",
    "sourceUrl": "https://www.notion.com/product/enterprise-search",
    "imageUrl": "",
    "captureHint": "Crop the hero underneath “Every answer, one search.”",
    "tags": [
      "ai",
      "enterprise",
      "video",
      "conversion"
    ],
    "batch": "curated-product-sites",
    "index": 97,
    "id": "097-demo-video-proof-cta"
  },
  {
    "title": "Template Arrow Link",
    "buttonLabel": "Get template →",
    "category": "Secondary/Ghost",
    "visualTrait": "Repeated arrow-ended template actions make resource exploration feel lightweight and browsable.",
    "sourceName": "Notion for Education",
    "sourceSite": "notion.com",
    "sourceUrl": "https://www.notion.com/product/notion-for-education",
    "imageUrl": "",
    "captureHint": "Crop the Student planner, Club home, or Habit tracker card with its Get template link.",
    "tags": [
      "template",
      "education",
      "arrow",
      "resource"
    ],
    "batch": "curated-product-sites",
    "index": 98,
    "id": "098-template-arrow-link"
  },
  {
    "title": "OS Download Segmented Switcher",
    "buttonLabel": "Mac / Linux / Windows",
    "category": "Toggle/Segmented",
    "visualTrait": "Small platform tabs sit beside a terminal-style install command, blending GUI choice with developer workflow.",
    "sourceName": "Warp downloads",
    "sourceSite": "warp.dev",
    "sourceUrl": "https://www.warp.dev/download",
    "imageUrl": "",
    "captureHint": "Crop the Agent CLI platform buttons and install-command block.",
    "tags": [
      "developer",
      "platform",
      "segmented",
      "terminal"
    ],
    "batch": "curated-product-sites",
    "index": 99,
    "id": "099-os-download-segmented-switcher"
  },
  {
    "title": "Agent Model Tab Strip",
    "buttonLabel": "Warp Agent / Claude Code / Codex / OpenCode / Gemini",
    "category": "Toggle/Segmented",
    "visualTrait": "A horizontal model selector turns product compatibility into a tactile tabbed interface.",
    "sourceName": "Warp Terminal",
    "sourceSite": "warp.dev",
    "sourceUrl": "https://www.warp.dev/terminal",
    "imageUrl": "",
    "captureHint": "Crop the agent-model selector directly above the terminal product imagery.",
    "tags": [
      "ai",
      "tabs",
      "developer",
      "segmented"
    ],
    "batch": "curated-product-sites",
    "index": 100,
    "id": "100-agent-model-tab-strip"
  },
  {
    "title": "Fintech dashboard action control",
    "buttonLabel": "Dashboard action (label not exposed)",
    "category": "Primary CTA",
    "visualTrait": "Compact dashboard action control within a finance interface; the project preview is presented as a Figma dashboard image.",
    "sourceName": "Fintech Dashboard UI/UX Design — Awais Arshad",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/234669371/Fintech-Dashboard-UIUX-Design",
    "imageUrl": "",
    "captureHint": "Single dashboard preview image near the top of the project.",
    "tags": [
      "fintech",
      "dashboard",
      "figma",
      "webapp"
    ],
    "batch": "expansion-behance",
    "index": 101,
    "id": "101-fintech-dashboard-action-control"
  },
  {
    "title": "Minimal fintech dashboard control",
    "buttonLabel": "Dashboard action (label not exposed)",
    "category": "Secondary/Ghost",
    "visualTrait": "Restrained action treatment set into an exploratory fintech dashboard UI.",
    "sourceName": "Fintech Dashboard Design — Ogenna Daniel",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/166003761/Fintech-Dashboard-Design",
    "imageUrl": "",
    "captureHint": "Main dashboard composition in the project preview.",
    "tags": [
      "fintech",
      "dashboard",
      "minimal",
      "uiux"
    ],
    "batch": "expansion-behance",
    "index": 102,
    "id": "102-minimal-fintech-dashboard-control"
  },
  {
    "title": "Ecommerce slider CTA",
    "buttonLabel": "Homepage slider action (label not exposed)",
    "category": "Commerce",
    "visualTrait": "Promotional CTA integrated into ecommerce homepage slider compositions.",
    "sourceName": "UI/UX Design for Ecommerce Website — Tauhid Abiad",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/117996733/UIUX-Design-for-Ecommerce-Website",
    "imageUrl": "",
    "captureHint": "Homepage With First Slider, Second Slider, and Third Slider images.",
    "tags": [
      "ecommerce",
      "slider",
      "homepage",
      "cta"
    ],
    "batch": "expansion-behance",
    "index": 103,
    "id": "103-ecommerce-slider-cta"
  },
  {
    "title": "Editorial shop product action",
    "buttonLabel": "Product action (label not exposed)",
    "category": "Commerce",
    "visualTrait": "Commerce action control shown as part of a polished full-site ecommerce UI study.",
    "sourceName": "Ecommerce UI/UX Design — Yuliya Yeryemyeyeva",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/144781911/Ecommerce-UIUX-Design",
    "imageUrl": "",
    "captureHint": "Product and storefront screen imagery in the project presentation.",
    "tags": [
      "ecommerce",
      "product",
      "webdesign",
      "uiux"
    ],
    "batch": "expansion-behance",
    "index": 104,
    "id": "104-editorial-shop-product-action"
  },
  {
    "title": "Landing-page purchase CTA",
    "buttonLabel": "Shop action (label not exposed)",
    "category": "Commerce",
    "visualTrait": "High-emphasis call-to-action placed in an ecommerce marketing landing-page layout.",
    "sourceName": "E-Commerce Landing Page UI/UX — Metehan Akdeniz",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/120367685/E-Commerce-Landing-Page-UIUX",
    "imageUrl": "",
    "captureHint": "Main ecommerce landing-page image at the top of the project.",
    "tags": [
      "ecommerce",
      "landing-page",
      "marketing",
      "cta"
    ],
    "batch": "expansion-behance",
    "index": 105,
    "id": "105-landing-page-purchase-cta"
  },
  {
    "title": "Discover link as brutalist CTA",
    "buttonLabel": "Click here to discover",
    "category": "Experimental/Motion",
    "visualTrait": "Direct text-led discovery call-to-action in a fictional one-page brutalist art-site prototype.",
    "sourceName": "BRUTALISM — Hani Ku",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/245814935/BRUTALISM",
    "imageUrl": "",
    "captureHint": "Opening project description and linked prototype area.",
    "tags": [
      "brutalist",
      "text-button",
      "figma",
      "editorial"
    ],
    "batch": "expansion-behance",
    "index": 106,
    "id": "106-discover-link-as-brutalist-cta"
  },
  {
    "title": "Streamlined UI toggle button",
    "buttonLabel": "Toggle state (label not exposed)",
    "category": "Toggle/Segmented",
    "visualTrait": "Standalone toggle-button exploration presented with a livestream/prototype embed.",
    "sourceName": "UI - Toggle Button Design — Brandon Groce",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/113002135/UI-Toggle-Button-Design",
    "imageUrl": "",
    "captureHint": "Embedded project content and toggle design artwork.",
    "tags": [
      "toggle",
      "button",
      "uiux",
      "prototype"
    ],
    "batch": "expansion-behance",
    "index": 107,
    "id": "107-streamlined-ui-toggle-button"
  },
  {
    "title": "Gaming commerce checkout action",
    "buttonLabel": "Shop/order action (label not exposed)",
    "category": "Commerce",
    "visualTrait": "Mobile ecommerce action control within gaming-accessory browse, cart, wishlist, product, and checkout flows.",
    "sourceName": "Go & Game UI/UX Layout — Jay Estacio",
    "sourceSite": "Behance",
    "sourceUrl": "https://www.behance.net/gallery/244332207/Go-Game-UIUX-Layout",
    "imageUrl": "",
    "captureHint": "Cart Page, Wish List Page, Product Page, and Checkout Page images.",
    "tags": [
      "gaming",
      "ecommerce",
      "checkout",
      "mobile"
    ],
    "batch": "expansion-behance",
    "index": 108,
    "id": "108-gaming-commerce-checkout-action"
  },
  {
    "title": "Left-aligned enterprise icon button",
    "buttonLabel": "Button with icon",
    "category": "Primary CTA",
    "visualTrait": "Square blue action with a left-aligned label and a utility icon anchored at the far edge.",
    "sourceName": "Carbon Design System — Button",
    "sourceSite": "Carbon Design System",
    "sourceUrl": "https://carbondesignsystem.com/components/button/code/",
    "batch": "expansion-systems",
    "index": 109,
    "id": "109-left-aligned-enterprise-icon-button"
  },
  {
    "title": "Critical commerce action",
    "buttonLabel": "Primary critical button",
    "category": "Destructive/Confirm",
    "visualTrait": "Polaris semantic action styling combines primary emphasis with a critical tone.",
    "sourceName": "Shopify Polaris — Web components",
    "sourceSite": "Shopify Polaris",
    "sourceUrl": "https://shopify.dev/docs/api/polaris/using-polaris-web-components",
    "batch": "expansion-systems",
    "index": 110,
    "id": "110-critical-commerce-action"
  },
  {
    "title": "Atlassian primary action",
    "buttonLabel": "Primary button",
    "category": "Primary CTA",
    "visualTrait": "Compact blue product button with restrained rounding and dense horizontal padding.",
    "sourceName": "Atlassian Design System — Button",
    "sourceSite": "Atlassian Design System",
    "sourceUrl": "https://atlassian.design/guidelines/product/components/buttons",
    "batch": "expansion-systems",
    "index": 111,
    "id": "111-atlassian-primary-action"
  },
  {
    "title": "Base high-contrast action",
    "buttonLabel": "Start ride",
    "category": "Primary CTA",
    "visualTrait": "Heavy black action treatment derived from Uber's high-contrast Base language.",
    "sourceName": "Base Web — Button",
    "sourceSite": "Base Web",
    "sourceUrl": "https://baseweb.design/components/button/",
    "batch": "expansion-systems",
    "index": 112,
    "id": "112-base-high-contrast-action"
  },
  {
    "title": "Lightning brand button",
    "buttonLabel": "Brand",
    "category": "Primary CTA",
    "visualTrait": "Salesforce blue brand control with optional leading or trailing utility icon.",
    "sourceName": "Salesforce Lightning — Button",
    "sourceSite": "Salesforce Lightning",
    "sourceUrl": "https://developer.salesforce.com/docs/platform/lightning-component-reference/guide/lightning-button.html?type=Example",
    "batch": "expansion-systems",
    "index": 113,
    "id": "113-lightning-brand-button"
  },
  {
    "title": "PatternFly warning action",
    "buttonLabel": "Warning",
    "category": "Destructive/Confirm",
    "visualTrait": "Pill-shaped warning action that uses amber emphasis without implying deletion.",
    "sourceName": "PatternFly — Button",
    "sourceSite": "PatternFly",
    "sourceUrl": "https://www.patternfly.org/components/button/",
    "batch": "expansion-systems",
    "index": 114,
    "id": "114-patternfly-warning-action"
  },
  {
    "title": "Elastic empty button",
    "buttonLabel": "Button",
    "category": "Secondary/Ghost",
    "visualTrait": "Low-chrome text action tuned for dense interfaces and narrow tool areas.",
    "sourceName": "Elastic UI — Button",
    "sourceSite": "Elastic UI",
    "sourceUrl": "https://eui.elastic.co/docs/components/navigation/buttons/button/",
    "batch": "expansion-systems",
    "index": 115,
    "id": "115-elastic-empty-button"
  },
  {
    "title": "Zendesk basic action",
    "buttonLabel": "Basic",
    "category": "Secondary/Ghost",
    "visualTrait": "Quiet workflow action with low visual weight beside primary and default variants.",
    "sourceName": "Zendesk Garden — Button",
    "sourceSite": "Zendesk Garden",
    "sourceUrl": "https://garden.zendesk.com/components/button/",
    "batch": "expansion-systems",
    "index": 116,
    "id": "116-zendesk-basic-action"
  },
  {
    "title": "Fiori semantic accept button",
    "buttonLabel": "Accept",
    "category": "Destructive/Confirm",
    "visualTrait": "Semantic positive state in a compact enterprise control family with text and icon variants.",
    "sourceName": "SAP Fiori — Button",
    "sourceSite": "SAP Fiori",
    "sourceUrl": "https://www.sap.com/design-system/fiori-design-web/v1-71/ui-elements/button/",
    "batch": "expansion-systems",
    "index": 117,
    "id": "117-fiori-semantic-accept-button"
  },
  {
    "title": "NHS transactional continue button",
    "buttonLabel": "Continue",
    "category": "Submit/Conversion",
    "visualTrait": "Large green rectangular action built for transactional journeys and strong accessibility.",
    "sourceName": "NHS Digital Service Manual — Buttons",
    "sourceSite": "NHS Design System",
    "sourceUrl": "https://service-manual.nhs.uk/design-system/components/buttons",
    "batch": "expansion-systems",
    "index": 118,
    "id": "118-nhs-transactional-continue-button"
  },
  {
    "title": "Canada start-task button",
    "buttonLabel": "Start",
    "category": "Navigation/Menu",
    "visualTrait": "Oversized government start control reserved for the beginning of a task or flow.",
    "sourceName": "GC Design System — Button",
    "sourceSite": "GC Design System",
    "sourceUrl": "https://design-system.canada.ca/en/components/button/",
    "batch": "expansion-systems",
    "index": 119,
    "id": "119-canada-start-task-button"
  },
  {
    "title": "VA directional continue action",
    "buttonLabel": "Continue",
    "category": "Accessibility/State",
    "visualTrait": "Accessible form progression button with explicit direction and a generous target area.",
    "sourceName": "VA.gov Design System — Button",
    "sourceSite": "VA.gov Design System",
    "sourceUrl": "https://design.va.gov/components/button/",
    "batch": "expansion-systems",
    "index": 120,
    "id": "120-va-directional-continue-action"
  },
  {
    "title": "Ontario wide secondary button",
    "buttonLabel": "Secondary - default",
    "category": "Secondary/Ghost",
    "visualTrait": "Wide outlined government action with a defined minimum width and generous padding.",
    "sourceName": "Ontario Design System — Buttons",
    "sourceSite": "Ontario Design System",
    "sourceUrl": "https://designsystem.ontario.ca/components/detail/buttons.html",
    "batch": "expansion-systems",
    "index": 121,
    "id": "121-ontario-wide-secondary-button"
  },
  {
    "title": "NSW danger confirmation",
    "buttonLabel": "Delete",
    "category": "Destructive/Confirm",
    "visualTrait": "Government-branded destructive action separated from brand and outline states.",
    "sourceName": "NSW Design System — Buttons",
    "sourceSite": "NSW Design System",
    "sourceUrl": "https://designsystem.nsw.gov.au/components/button/index.html",
    "batch": "expansion-systems",
    "index": 122,
    "id": "122-nsw-danger-confirmation"
  },
  {
    "title": "Bootstrap outline warning",
    "buttonLabel": "Warning",
    "category": "Secondary/Ghost",
    "visualTrait": "Familiar outlined semantic button whose border and label carry the warning color.",
    "sourceName": "Bootstrap — Buttons",
    "sourceSite": "Bootstrap",
    "sourceUrl": "https://getbootstrap.com/docs/5.3/components/buttons/",
    "batch": "expansion-systems",
    "index": 123,
    "id": "123-bootstrap-outline-warning"
  },
  {
    "title": "Generic close glyph button",
    "buttonLabel": "Close",
    "category": "Icon",
    "visualTrait": "Minimal icon-only dismiss control with no visible container until interaction.",
    "sourceName": "Bootstrap — Close button",
    "sourceSite": "Bootstrap",
    "sourceUrl": "https://getbootstrap.com/docs/5.3/components/close-button/",
    "batch": "expansion-systems",
    "index": 124,
    "id": "124-generic-close-glyph-button"
  },
  {
    "title": "Dashed add-action button",
    "buttonLabel": "Dashed Button",
    "category": "Secondary/Ghost",
    "visualTrait": "Dashed border communicates an additive or provisional action distinct from default controls.",
    "sourceName": "Ant Design — Button",
    "sourceSite": "Ant Design",
    "sourceUrl": "https://ant.design/components/button/",
    "batch": "expansion-systems",
    "index": 125,
    "id": "125-dashed-add-action-button"
  },
  {
    "title": "Attached split-save control",
    "buttonLabel": "Save",
    "category": "Navigation/Menu",
    "visualTrait": "Primary save action attached to a compact menu trigger for related commands.",
    "sourceName": "Chakra UI — Button",
    "sourceSite": "Chakra UI",
    "sourceUrl": "https://chakra-ui.com/docs/components/button",
    "batch": "expansion-systems",
    "index": 126,
    "id": "126-attached-split-save-control"
  },
  {
    "title": "Mantine sectioned button",
    "buttonLabel": "Button",
    "category": "Primary CTA",
    "visualTrait": "Filled action with optional leading and trailing sections integrated into its capsule.",
    "sourceName": "Mantine — Button",
    "sourceSite": "Mantine",
    "sourceUrl": "https://mantine.dev/core/button/",
    "batch": "expansion-systems",
    "index": 127,
    "id": "127-mantine-sectioned-button"
  },
  {
    "title": "Radix soft full-radius action",
    "buttonLabel": "Edit profile",
    "category": "Secondary/Ghost",
    "visualTrait": "Soft tinted action with a fully rounded radius and compact type scale.",
    "sourceName": "Radix Themes — Button",
    "sourceSite": "Radix Themes",
    "sourceUrl": "https://www.radix-ui.com/themes/docs/components/button",
    "batch": "expansion-systems",
    "index": 128,
    "id": "128-radix-soft-full-radius-action"
  },
  {
    "title": "Gradient social-payment button",
    "buttonLabel": "Pay with PayPal",
    "category": "Social/Share",
    "visualTrait": "Utility-library treatment combining brand color, iconography, and a full action label.",
    "sourceName": "Flowbite — Buttons",
    "sourceSite": "Flowbite",
    "sourceUrl": "https://flowbite.com/docs/components/buttons/",
    "batch": "expansion-systems",
    "index": 129,
    "id": "129-gradient-social-payment-button"
  },
  {
    "title": "Material elevated button",
    "buttonLabel": "Elevated",
    "category": "Primary CTA",
    "visualTrait": "Tonal capsule lifted with subtle elevation rather than a hard outline.",
    "sourceName": "Material Web — Button",
    "sourceSite": "Material Web",
    "sourceUrl": "https://material-web.dev/components/button/",
    "batch": "expansion-systems",
    "index": 130,
    "id": "130-material-elevated-button"
  },
  {
    "title": "Shoelace loading button",
    "buttonLabel": "Loading",
    "category": "Accessibility/State",
    "visualTrait": "Web-component action that preserves its container while swapping content for progress.",
    "sourceName": "Shoelace — Button",
    "sourceSite": "Shoelace",
    "sourceUrl": "https://shoelace.style/components/button",
    "batch": "expansion-systems",
    "index": 131,
    "id": "131-shoelace-loading-button"
  },
  {
    "title": "Shadcn destructive action",
    "buttonLabel": "Destructive",
    "category": "Destructive/Confirm",
    "visualTrait": "Compact red action in a code-owned component set with restrained corner rounding.",
    "sourceName": "shadcn/ui — Button",
    "sourceSite": "shadcn/ui",
    "sourceUrl": "https://ui.shadcn.com/docs/components/base/button",
    "batch": "expansion-systems",
    "index": 132,
    "id": "132-shadcn-destructive-action"
  },
  {
    "title": "Daisy glass button",
    "buttonLabel": "Glass button",
    "category": "Experimental/Motion",
    "visualTrait": "Translucent glass treatment designed to react to colorful or photographic backgrounds.",
    "sourceName": "daisyUI — Button",
    "sourceSite": "daisyUI",
    "sourceUrl": "https://daisyui.com/components/button/",
    "batch": "expansion-systems",
    "index": 133,
    "id": "133-daisy-glass-button"
  },
  {
    "title": "Hero shadow button",
    "buttonLabel": "Press me",
    "category": "Primary CTA",
    "visualTrait": "Rounded React action whose colored shadow adds emphasis beyond its filled surface.",
    "sourceName": "HeroUI — Button",
    "sourceSite": "HeroUI",
    "sourceUrl": "https://heroui.com/en/docs/react/components/button",
    "batch": "expansion-systems",
    "index": 134,
    "id": "134-hero-shadow-button"
  },
  {
    "title": "Unstyled accessible primitive",
    "buttonLabel": "Button",
    "category": "Accessibility/State",
    "visualTrait": "Behavior-first accessible primitive intended to inherit a product's own visual language.",
    "sourceName": "Kobalte — Button",
    "sourceSite": "Kobalte",
    "sourceUrl": "https://kobalte.dev/docs/core/components/button",
    "batch": "expansion-systems",
    "index": 135,
    "id": "135-unstyled-accessible-primitive"
  },
  {
    "title": "Nuxt trailing-icon button",
    "buttonLabel": "Continue",
    "category": "Navigation/Menu",
    "visualTrait": "Rounded action with a directional icon placed after the label for clear progression.",
    "sourceName": "Nuxt UI — Button",
    "sourceSite": "Nuxt UI",
    "sourceUrl": "https://ui.nuxt.com/docs/components/button",
    "batch": "expansion-systems",
    "index": 136,
    "id": "136-nuxt-trailing-icon-button"
  },
  {
    "title": "PrimeVue raised button",
    "buttonLabel": "Primary",
    "category": "Primary CTA",
    "visualTrait": "Conventional filled action made more prominent through a distinct raised shadow state.",
    "sourceName": "PrimeVue — Button",
    "sourceSite": "PrimeVue",
    "sourceUrl": "https://primevue.dev/button/",
    "batch": "expansion-systems",
    "index": 137,
    "id": "137-primevue-raised-button"
  },
  {
    "title": "Clarity inverse action",
    "buttonLabel": "Inverse",
    "category": "Secondary/Ghost",
    "visualTrait": "Light outline and text treatment intended specifically for dark application surfaces.",
    "sourceName": "Clarity Design System — Button",
    "sourceSite": "Clarity Design System",
    "sourceUrl": "https://clarity.design/documentation/button",
    "batch": "expansion-systems",
    "index": 138,
    "id": "138-clarity-inverse-action"
  },
  {
    "title": "Vanilla processing button",
    "buttonLabel": "Processing",
    "category": "Accessibility/State",
    "visualTrait": "Disabled progress state that keeps the action's original width to prevent layout shift.",
    "sourceName": "Vanilla Framework — Buttons",
    "sourceSite": "Vanilla Framework",
    "sourceUrl": "https://vanillaframework.io/docs/patterns/buttons",
    "batch": "expansion-systems",
    "index": 139,
    "id": "139-vanilla-processing-button"
  },
  {
    "title": "Nord dashed filter action",
    "buttonLabel": "Filter",
    "category": "Toggle/Segmented",
    "visualTrait": "Dashed compact control reserved for actions that trigger filtering.",
    "sourceName": "Nord Design System — Button",
    "sourceSite": "Nord Design System",
    "sourceUrl": "https://nordhealth.design/components/button/",
    "batch": "expansion-systems",
    "index": 140,
    "id": "140-nord-dashed-filter-action"
  },
  {
    "title": "Bootstrap attached button group",
    "buttonLabel": "Left / Middle / Right",
    "category": "Toggle/Segmented",
    "visualTrait": "Three rectangular actions share borders to read as a single segmented group.",
    "sourceName": "Bootstrap — Button group",
    "sourceSite": "Bootstrap",
    "sourceUrl": "https://getbootstrap.com/docs/5.3/components/button-group/",
    "batch": "expansion-systems",
    "index": 141,
    "id": "141-bootstrap-attached-button-group"
  },
  {
    "title": "Duet negative-surface button",
    "buttonLabel": "Negative",
    "category": "Secondary/Ghost",
    "visualTrait": "High-contrast light action created for dark backgrounds and illustration surfaces.",
    "sourceName": "Duet Design System — Button",
    "sourceSite": "Duet Design System",
    "sourceUrl": "https://www.duetds.com/components/button/",
    "batch": "expansion-systems",
    "index": 142,
    "id": "142-duet-negative-surface-button"
  },
  {
    "title": "Helsinki success button",
    "buttonLabel": "Success",
    "category": "Destructive/Confirm",
    "visualTrait": "Explicit success-state action in a civic component family with primary and supplementary peers.",
    "sourceName": "Helsinki Design System — Button",
    "sourceSite": "Helsinki Design System",
    "sourceUrl": "https://hds.hel.fi/components/button/",
    "batch": "expansion-systems",
    "index": 143,
    "id": "143-helsinki-success-button"
  },
  {
    "title": "Porsche icon-only action",
    "buttonLabel": "Some label",
    "category": "Icon",
    "visualTrait": "Precision automotive control that can collapse to an icon while retaining an accessible label.",
    "sourceName": "Porsche Design System — Button",
    "sourceSite": "Porsche Design System",
    "sourceUrl": "https://designsystem.porsche.com/v4/components/button/configurator/",
    "batch": "expansion-systems",
    "index": 144,
    "id": "144-porsche-icon-only-action"
  },
  {
    "title": "Thumbprint caution button",
    "buttonLabel": "Caution",
    "category": "Destructive/Confirm",
    "visualTrait": "Marketplace action using a dedicated caution theme alongside primary, tertiary, and solid states.",
    "sourceName": "Thumbprint — Button",
    "sourceSite": "Thumbprint",
    "sourceUrl": "https://thumbprint.design/components/button/v1/react",
    "batch": "expansion-systems",
    "index": 145,
    "id": "145-thumbprint-caution-button"
  },
  {
    "title": "Cedar commerce action",
    "buttonLabel": "Add to cart",
    "category": "Commerce",
    "visualTrait": "Outdoor-retail action language with generous touch sizing and direct commerce labeling.",
    "sourceName": "REI Cedar — Buttons",
    "sourceSite": "REI Cedar",
    "sourceUrl": "https://rei.github.io/rei-cedar-docs/components/buttons/",
    "batch": "expansion-systems",
    "index": 146,
    "id": "146-cedar-commerce-action"
  },
  {
    "title": "Morningstar primary button",
    "buttonLabel": "Primary",
    "category": "Primary CTA",
    "visualTrait": "Financial-product action with disciplined spacing, weight, and semantic hierarchy.",
    "sourceName": "Morningstar Design System — Button",
    "sourceSite": "Morningstar Design System",
    "sourceUrl": "https://designsystem.morningstar.com/components/button/",
    "batch": "expansion-systems",
    "index": 147,
    "id": "147-morningstar-primary-button"
  },
  {
    "title": "Queensland icon-trailing action",
    "buttonLabel": "Trailing icon",
    "category": "Accessibility/State",
    "visualTrait": "Civic action with a 48-pixel target and a trailing icon that reinforces the outcome.",
    "sourceName": "Queensland Government Design System — Button",
    "sourceSite": "Queensland Government Design System",
    "sourceUrl": "https://www.designsystem.qld.gov.au/components/button",
    "batch": "expansion-systems",
    "index": 148,
    "id": "148-queensland-icon-trailing-action"
  },
  {
    "title": "Spectrum static outline button",
    "buttonLabel": "Click me",
    "category": "Secondary/Ghost",
    "visualTrait": "Static white outline treatment designed to stay legible over imagery and dark color fields.",
    "sourceName": "Spectrum Web Components — Button",
    "sourceSite": "Spectrum Web Components",
    "sourceUrl": "https://opensource.adobe.com/spectrum-web-components/components/button/",
    "batch": "expansion-systems",
    "index": 149,
    "id": "149-spectrum-static-outline-button"
  },
  {
    "title": "Lion form-submit primitive",
    "buttonLabel": "Submit",
    "category": "Submit/Conversion",
    "visualTrait": "Accessible web-component primitive with native-form submit behavior and an enlarged click area.",
    "sourceName": "Lion UI — Button",
    "sourceSite": "Lion UI",
    "sourceUrl": "https://lion.js.org/components/button/overview/",
    "batch": "expansion-systems",
    "index": 150,
    "id": "150-lion-form-submit-primitive"
  }
];
